"""Regen v2.3.2 templates from v2.3.1 on-disk templates, removing deprecated blocks."""
import re
import sys
from pathlib import Path

REPO = Path("/Users/peteromalley/Documents/.megaplan-worktrees/vibecomfy-v232")

TEMPLATES = [
    "ready_templates/video/wan_i2v.py",
    "ready_templates/image/qwen_image_2512.py",
    "ready_templates/audio/ace_step_1_5_t2a_song.py",
    "ready_templates/edit/qwen_image_edit.py",
    "ready_templates/video/ltx2_3_first_last_frame_travel_iclora_control.py",
]

for template_path in TEMPLATES:
    path = REPO / template_path
    source = path.read_text(encoding="utf-8")
    original = source

    # 1. Extract PRIVATE_KNOBS and inline values
    pk_match = re.search(r"PRIVATE_KNOBS: dict\[str, object\] = \{([^}]*)\}", source, re.DOTALL)
    private_knobs = {}
    if pk_match:
        body = pk_match.group(1)
        for item in re.findall(r"'(\w+)':\s*([^,\n]+)", body):
            val = item[1].strip()
            private_knobs[item[0]] = val
        # Remove PRIVATE_KNOBS block
        source = source.replace(pk_match.group(0), "")
        # Inline references
        for key, val in private_knobs.items():
            source = source.replace(f"PRIVATE_KNOBS['{key}']", val)
            source = source.replace(f'PRIVATE_KNOBS["{key}"]', val)

    # 2. Extract OUTPUT_PREFIX value
    op_match = re.search(r"^OUTPUT_PREFIX\s*=\s*('[^']*'|\"[^\"]*\")", source, re.MULTILINE)
    output_prefix_val = None
    if op_match:
        output_prefix_val = op_match.group(1)
        # Remove OUTPUT_PREFIX line
        source = source.replace(op_match.group(0), "")
        # Replace OUTPUT_PREFIX references in ReadyMetadata.build
        source = source.replace("output_prefix=OUTPUT_PREFIX", f"output_prefix={output_prefix_val}")
        # Replace OUTPUT_PREFIX references in finalize footer
        source = source.replace("filename_prefix=OUTPUT_PREFIX", f"filename_prefix={output_prefix_val}")

    # 3. Extract READY_REQUIREMENTS and merge into ReadyMetadata.build
    rr_match = re.search(r"READY_REQUIREMENTS: dict\[str, object\] = (\{[^}]+\})", source, re.DOTALL)
    if rr_match:
        rr_body = rr_match.group(1)
        source = source.replace(rr_match.group(0), "")
        # Remove requirements=READY_REQUIREMENTS from finalize
        source = source.replace(", requirements=READY_REQUIREMENTS", "")
        source = source.replace("requirements=READY_REQUIREMENTS,", "")
        source = source.replace("requirements=READY_REQUIREMENTS", "")
        # If requirements is non-empty dict, merge into ReadyMetadata.build
        if rr_body.strip() not in ("{}", "{  }"):
            if output_prefix_val:
                source = source.replace(
                    f"    output_prefix={output_prefix_val},\n",
                    f"    output_prefix={output_prefix_val},\n    requirements={rr_body},\n",
                )

    # 4. Remove blank lines left by removals (collapsing 3+ blank lines to 2)
    source = re.sub(r'\n\n\n+', '\n\n', source)

    # 5. Replace legacy narrative markers with canonical provenance form
    source = source.replace(
        "# vibecomfy: narrative (generated by tools/narrate_template.py)",
        '# generated by vibecomfy port convert; see READY_METADATA["provenance"]',
    )
    source = source.replace(
        "# vibecomfy: narrative (generated by tools/narrate_template.py @ 0.1.0+g9c5810f+dirty)",
        '# generated by vibecomfy port convert; see READY_METADATA["provenance"]',
    )

    if source != original:
        path.write_text(source, encoding="utf-8")
        print(f"Updated: {template_path}")
    else:
        print(f"No changes: {template_path}")
