"""Ready-template Python emission package."""
from __future__ import annotations

from vibecomfy.porting import emitter
from vibecomfy.porting.emit.entrypoints import (
    emit_agent_edit_python,
    emit_ready_template_python,
    emit_scratchpad_python,
    format_as_python,
)
from vibecomfy.porting.emit.signatures import (
    EmissionDiagnostic,
    EmissionSeverity,
    InputSignatureField,
    NodeSignatureRow,
    OutputSignatureField,
    READABILITY_WARNING_AVOIDABLE_POSITIONAL_OUTPUT,
    READABILITY_WARNING_CODES,
    READABILITY_WARNING_GENERATED_TEMPLATE_NOT_FORMATTED,
    READABILITY_WARNING_GENERATED_VARIABLE_NAME_TOO_LONG,
    READABILITY_WARNING_HIDDEN_MODEL_FILENAME,
    READABILITY_WARNING_LOCAL_HELPER_COPY_IN_STRICT_TEMPLATE,
    READABILITY_WARNING_LOCKED_VARIABLE_ALIAS_COLLISION,
    READABILITY_WARNING_LOCKED_VARIABLE_ALIAS_INVALID,
    READABILITY_WARNING_LOCKED_VARIABLE_ALIAS_MISSING,
    READABILITY_WARNING_LOCKED_VARIABLE_UID_COLLISION,
    READABILITY_WARNING_LONG_ONE_LINE_NODE_CALL,
    READABILITY_WARNING_OUTPUT_NAME_AMBIGUITY,
    READABILITY_WARNING_SCHEMA_BACKED_WIDGET_ALIAS_NOT_RESOLVED,
    emit_available_node_signatures,
    filter_signature_rows_to_in_graph_nodes,
    format_signature_rows,
)
from vibecomfy.porting.emit.node_kwargs import apply_overrides, node_kwargs
from vibecomfy.porting.emit.formatting import format_kwargs_block, format_metadata_dict, format_value
from vibecomfy.porting.emit.naming import (
    compute_variable_names,
    connection_role_name,
    empty_text_role,
    safe_var,
    topological_node_order,
)
from vibecomfy.porting.emit.ui import (
    WidgetShapeEvidence,
    _normalize_pinned_node_link_refs,
    _raw_ui_payload_for_pin,
    default_output_path,
    derive_widget_shape_evidence,
    emit_ui_json,
    extract_raw_ui_node_map,
    materialize_litegraph_node,
    offline_emitter_normalizer_self_consistency_check,
    structural_validate,
)

__all__ = [
    "EmissionDiagnostic",
    "EmissionSeverity",
    "READABILITY_WARNING_AVOIDABLE_POSITIONAL_OUTPUT",
    "READABILITY_WARNING_OUTPUT_NAME_AMBIGUITY",
    "READABILITY_WARNING_SCHEMA_BACKED_WIDGET_ALIAS_NOT_RESOLVED",
    "READABILITY_WARNING_HIDDEN_MODEL_FILENAME",
    "READABILITY_WARNING_LOCAL_HELPER_COPY_IN_STRICT_TEMPLATE",
    "READABILITY_WARNING_LONG_ONE_LINE_NODE_CALL",
    "READABILITY_WARNING_GENERATED_TEMPLATE_NOT_FORMATTED",
    "READABILITY_WARNING_GENERATED_VARIABLE_NAME_TOO_LONG",
    "READABILITY_WARNING_LOCKED_VARIABLE_ALIAS_INVALID",
    "READABILITY_WARNING_LOCKED_VARIABLE_ALIAS_COLLISION",
    "READABILITY_WARNING_LOCKED_VARIABLE_ALIAS_MISSING",
    "READABILITY_WARNING_LOCKED_VARIABLE_UID_COLLISION",
    "READABILITY_WARNING_CODES",
    "NodeSignatureRow",
    "InputSignatureField",
    "OutputSignatureField",
    "emit_available_node_signatures",
    "filter_signature_rows_to_in_graph_nodes",
    "format_signature_rows",
    "format_as_python",
    "emit_ready_template_python",
    "emit_agent_edit_python",
    "emit_scratchpad_python",
    "apply_overrides",
    "node_kwargs",
    "format_kwargs_block",
    "format_metadata_dict",
    "format_value",
    "compute_variable_names",
    "connection_role_name",
    "empty_text_role",
    "safe_var",
    "topological_node_order",
    "WidgetShapeEvidence",
    "derive_widget_shape_evidence",
    "extract_raw_ui_node_map",
    "materialize_litegraph_node",
    "_normalize_pinned_node_link_refs",
    "_raw_ui_payload_for_pin",
    "emit_ui_json",
    "offline_emitter_normalizer_self_consistency_check",
    "structural_validate",
    "default_output_path",
    "emitter",
]
