from __future__ import annotations

import os
from pathlib import Path

import pytest

from vibecomfy.node_packs import (
    LockEntry,
    canonical_pack_schema_projection,
    compute_schema_hash,
    read_lockfile,
    upsert_lockfile_entry,
    write_lockfile,
)


def test_lockfile_legacy_round_trip_to_text(tmp_path: Path) -> None:
    lockfile = tmp_path / "custom_nodes.lock"
    lockfile.write_text("ComfyUI-KJNodes abc123 https://example.test/kj.git\n", encoding="utf-8")

    entries = read_lockfile(lockfile)
    assert entries == [
        LockEntry(
            name="ComfyUI-KJNodes",
            git_commit_sha="abc123",
            url="https://example.test/kj.git",
        )
    ]

    write_lockfile(entries, lockfile)
    written = lockfile.read_text(encoding="utf-8")
    assert "ComfyUI-KJNodes abc123 https://example.test/kj.git" in written
    assert "[nodepacks." not in written
    assert read_lockfile(lockfile) == entries


def test_lockfile_reads_git_sha_synonym_and_absent_path(tmp_path: Path) -> None:
    lockfile = tmp_path / "custom_nodes.lock"
    lockfile.write_text(
        """
[nodepacks.LegacyName]
git_sha = "abc123"
url = "https://example.test/legacy.git"
semantic_label = "main"

[nodepacks.LegacyName.source_sha256]
"nodes.py" = "deadbeef"
""",
        encoding="utf-8",
    )

    assert read_lockfile(lockfile) == [
        LockEntry(
            name="LegacyName",
            git_commit_sha="abc123",
            url="https://example.test/legacy.git",
            semantic_label="main",
            source_sha256={"nodes.py": "deadbeef"},
        )
    ]
    assert read_lockfile(tmp_path / "missing.lock") == []


def test_upsert_lockfile_entry_appends_to_legacy_lockfile(tmp_path: Path) -> None:
    lockfile = tmp_path / "custom_nodes.lock"
    lockfile.write_text(
        "\n".join(
            [
                "ComfyUI-KJNodes abc123 https://example.test/kj.git",
                "ComfyUI-WanVideoWrapper def456 https://example.test/wan.git",
            ]
        ),
        encoding="utf-8",
    )

    upsert_lockfile_entry(
        LockEntry(
            name="ComfyUI-QwenTTS",
            git_commit_sha="fedcba",
            url="https://example.test/qwen.git",
        ),
        lockfile,
    )

    assert read_lockfile(lockfile) == [
        LockEntry(
            name="ComfyUI-KJNodes",
            git_commit_sha="abc123",
            url="https://example.test/kj.git",
        ),
        LockEntry(
            name="ComfyUI-QwenTTS",
            git_commit_sha="fedcba",
            url="https://example.test/qwen.git",
        ),
        LockEntry(
            name="ComfyUI-WanVideoWrapper",
            git_commit_sha="def456",
            url="https://example.test/wan.git",
        ),
    ]
    assert lockfile.read_text(encoding="utf-8").splitlines() == [
        "# Generated by vibecomfy nodes lock.",
        "ComfyUI-KJNodes abc123 https://example.test/kj.git",
        "ComfyUI-QwenTTS fedcba https://example.test/qwen.git",
        "ComfyUI-WanVideoWrapper def456 https://example.test/wan.git",
    ]


def test_upsert_lockfile_entry_replaces_existing_name(tmp_path: Path) -> None:
    lockfile = tmp_path / "custom_nodes.lock"
    lockfile.write_text(
        "\n".join(
            [
                "ComfyUI-KJNodes abc123 https://example.test/kj.git",
                "ComfyUI-WanVideoWrapper def456 https://example.test/wan.git",
            ]
        ),
        encoding="utf-8",
    )

    upsert_lockfile_entry(
        LockEntry(
            name="ComfyUI-KJNodes",
            git_commit_sha="updated",
            url="https://example.test/kj-updated.git",
        ),
        lockfile,
    )

    assert read_lockfile(lockfile) == [
        LockEntry(
            name="ComfyUI-KJNodes",
            git_commit_sha="updated",
            url="https://example.test/kj-updated.git",
        ),
        LockEntry(
            name="ComfyUI-WanVideoWrapper",
            git_commit_sha="def456",
            url="https://example.test/wan.git",
        ),
    ]
    assert lockfile.read_text(encoding="utf-8").splitlines() == [
        "# Generated by vibecomfy nodes lock.",
        "ComfyUI-KJNodes updated https://example.test/kj-updated.git",
        "ComfyUI-WanVideoWrapper def456 https://example.test/wan.git",
    ]


def test_lockfile_toml_round_trip_with_class_schema(tmp_path: Path) -> None:
    """Phase 5a: class_schema_sha256 persists in TOML and rereads correctly."""
    lockfile = tmp_path / "custom_nodes.lock"

    write_lockfile(
        [
            LockEntry(
                name="ComfyUI-KJNodes",
                git_commit_sha="abc123",
                url="https://example.test/kj.git",
                class_schema_sha256="deadbeef1234",
            ),
        ],
        lockfile,
    )

    raw = lockfile.read_text(encoding="utf-8")
    # Written as TOML because class_schema_sha256 is present.
    assert "[nodepacks.ComfyUI-KJNodes]" in raw
    assert 'class_schema_sha256 = "deadbeef1234"' in raw

    entries = read_lockfile(lockfile)
    assert entries == [
        LockEntry(
            name="ComfyUI-KJNodes",
            git_commit_sha="abc123",
            url="https://example.test/kj.git",
            class_schema_sha256="deadbeef1234",
        ),
    ]

    # Round-trip: rewrite and verify it stays.
    write_lockfile(entries, lockfile)
    again = read_lockfile(lockfile)
    assert again == entries


def test_lockfile_toml_with_source_and_schema_sha256(tmp_path: Path) -> None:
    """Phase 5a: both source_sha256 and class_schema_sha256 survive round-trip."""
    lockfile = tmp_path / "custom_nodes.lock"

    write_lockfile(
        [
            LockEntry(
                name="ComfyUI-KJNodes",
                git_commit_sha="abc123",
                url="https://example.test/kj.git",
                source_sha256={"nodes.py": "beef1111"},
                class_schema_sha256="cafe2222",
            ),
            LockEntry(
                name="ComfyUI-WanVideoWrapper",
                git_commit_sha="def456",
                url="https://example.test/wan.git",
                source_sha256={"requirements.txt": "feed3333"},
            ),
        ],
        lockfile,
    )

    entries = read_lockfile(lockfile)
    assert len(entries) == 2

    kj = next(e for e in entries if e.name == "ComfyUI-KJNodes")
    assert kj.source_sha256 == {"nodes.py": "beef1111"}
    assert kj.class_schema_sha256 == "cafe2222"

    wan = next(e for e in entries if e.name == "ComfyUI-WanVideoWrapper")
    assert wan.source_sha256 == {"requirements.txt": "feed3333"}
    assert wan.class_schema_sha256 is None

    # Rewrite and verify all values survive.
    write_lockfile(entries, lockfile)
    again = read_lockfile(lockfile)
    assert again == entries


def test_lockfile_rich_toml_round_trip_with_v24_identity_fields(tmp_path: Path) -> None:
    lockfile = tmp_path / "custom_nodes.lock"
    entry = LockEntry(
        name="ComfyUI-KJNodes",
        slug="comfyui-kjnodes",
        source="comfy-registry",
        version="1.2.3",
        commit="abc123",
        url="https://github.com/kijai/ComfyUI-KJNodes.git",
        schema_hash="feedface",
        class_set=("ZNode", "ImageResizeKJv2", "ImageResizeKJv2"),
        last_seen_at="2026-05-20T00:00:00Z",
        pip_packages=("opencv-python-headless", "onnx", "onnx"),
    )

    write_lockfile([entry], lockfile)

    raw = lockfile.read_text(encoding="utf-8")
    assert "[nodepacks.ComfyUI-KJNodes]" in raw
    assert 'slug = "comfyui-kjnodes"' in raw
    assert 'source = "comfy-registry"' in raw
    assert 'version = "1.2.3"' in raw
    assert 'commit = "abc123"' in raw
    assert 'schema_hash = "feedface"' in raw
    assert 'class_set = ["ImageResizeKJv2", "ZNode"]' in raw
    assert 'pip_packages = ["onnx", "opencv-python-headless"]' in raw

    assert read_lockfile(lockfile) == [
        LockEntry(
            name="ComfyUI-KJNodes",
            git_commit_sha="abc123",
            slug="comfyui-kjnodes",
            source="comfy-registry",
            version="1.2.3",
            commit="abc123",
            url="https://github.com/kijai/ComfyUI-KJNodes.git",
            schema_hash="feedface",
            class_schema_sha256="feedface",
            class_set=("ImageResizeKJv2", "ZNode"),
            last_seen_at="2026-05-20T00:00:00Z",
            pip_packages=("onnx", "opencv-python-headless"),
        )
    ]


def test_lockfile_reads_local_rich_entry_without_git_commit(tmp_path: Path) -> None:
    lockfile = tmp_path / "custom_nodes.lock"
    lockfile.write_text(
        """
[nodepacks.LocalPack]
source = "local"
path = "../LocalPack"
class_set = ["BetaNode", "AlphaNode"]
""",
        encoding="utf-8",
    )

    assert read_lockfile(lockfile) == [
        LockEntry(
            name="LocalPack",
            slug="LocalPack",
            source="local",
            path="../LocalPack",
            class_set=("AlphaNode", "BetaNode"),
        )
    ]


def test_known_node_pack_cache_invalidates_same_size_same_mtime_replacement(
    tmp_path: Path,
) -> None:
    from vibecomfy.node_packs import clear_known_node_packs_cache, get_known_node_packs

    lockfile = tmp_path / "custom_nodes.lock"
    first = """[nodepacks.PackOne]
source = "local"
path = "."
class_set = ["NodeOne"]
"""
    second = """[nodepacks.PackTwo]
source = "local"
path = "."
class_set = ["NodeTwo"]
"""
    assert len(first) == len(second)
    lockfile.write_text(first, encoding="utf-8")
    original_mtime_ns = lockfile.stat().st_mtime_ns
    clear_known_node_packs_cache()
    assert any(pack.name == "PackOne" for pack in get_known_node_packs(lockfile))

    lockfile.write_text(second, encoding="utf-8")
    os.utime(lockfile, ns=(original_mtime_ns, original_mtime_ns))
    refreshed = get_known_node_packs(lockfile)
    assert any(pack.name == "PackTwo" for pack in refreshed)
    assert not any(pack.name == "PackOne" for pack in refreshed)
    clear_known_node_packs_cache()


def test_known_node_pack_cache_does_not_hide_malformed_lock(tmp_path: Path) -> None:
    from vibecomfy.node_packs import get_known_node_packs

    lockfile = tmp_path / "custom_nodes.lock"
    lockfile.write_text(
        "[nodepacks.Broken]\nsource = \"git\"\ncommit = [\n",
        encoding="utf-8",
    )

    with pytest.raises(ValueError):
        get_known_node_packs(lockfile)


@pytest.mark.parametrize(
    ("body", "message"),
    [
        (
            '[nodepacks.Bad]\nsource = "git"\nurl = "https://example.test/bad.git"\n',
            "git_commit_sha",
        ),
        (
            '[nodepacks.Bad]\nsource = "git"\ncommit = "abc"\n',
            "url",
        ),
        (
            '[nodepacks.Bad]\nsource = "local"\n',
            "path",
        ),
        (
            '[nodepacks.Bad]\nsource = ["git"]\ncommit = "abc"\nurl = "x"\n',
            "source must be a string",
        ),
        (
            '[nodepacks.Bad]\nsource = "git"\ncommit = ["abc"]\nurl = "x"\n',
            "commit must be a string",
        ),
        (
            '[nodepacks.Bad]\nsource = "git"\ncommit = "abc"\nurl = 3\n',
            "url must be a string",
        ),
    ],
)
def test_lockfile_rejects_malformed_required_fields(
    tmp_path: Path, body: str, message: str,
) -> None:
    lockfile = tmp_path / "custom_nodes.lock"
    lockfile.write_text(body, encoding="utf-8")
    with pytest.raises(ValueError, match=message):
        read_lockfile(lockfile)


def test_schema_hash_projection_is_stable_and_limited_to_contract_fields() -> None:
    schema_a = {
        "ExampleNode": {
            "input": {
                "required": {
                    "prompt": ("STRING", {"default": "a"}),
                    "steps": ("INT", {"default": 20, "min": 1}),
                },
                "optional": {"seed": ("INT", {"default": 7})},
                "hidden": {"auth": "TOKEN"},
            },
            "output": ["IMAGE"],
            "output_name": ["image"],
            "ignored_runtime_noise": "changes",
        }
    }
    schema_b = {
        "ExampleNode": {
            "ignored_runtime_noise": "different",
            "output_name": ["image"],
            "output": ["IMAGE"],
            "input": {
                "hidden": {"auth": "TOKEN"},
                "optional": {"seed": ("INT", {"default": 7})},
                "required": {
                    "steps": ("INT", {"min": 1, "default": 20}),
                    "prompt": ("STRING", {"default": "a"}),
                },
            },
        }
    }

    assert canonical_pack_schema_projection(schema_a) == canonical_pack_schema_projection(schema_b)
    assert compute_schema_hash(schema_a) == compute_schema_hash(schema_b)
    assert len(compute_schema_hash(schema_a)) == 64
