"""Tests for tools/class_inventory_audit.py.

T-024: the audit tool must consume the node-pack lockfile through the
canonical ``vibecomfy.node_packs._lockfile.read_lockfile`` reader instead of
hand-parsing TOML, so it cannot drift from the lock format the rest of the
package writes.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

import tools.class_inventory_audit as audit

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOL_PATH = REPO_ROOT / "tools" / "class_inventory_audit.py"

# Legacy-style template: the audit extractor matches node(wf, ...) /
# wf.node(...) call patterns, so a fixture template (rather than the
# branch's bare-constructor ready templates) keeps extraction deterministic.
# The referenced classes are chosen from the repo's real lock so the
# pack-attribution path is exercised end to end.
_FIXTURE_TEMPLATE = """\
def build(wf):
    node(wf, 'DualCLIPLoaderGGUF', 'gguf1')
    wf.node('Note', 'note1')
    node(wf, 'KSampler', 'k1')
"""


def _run_audit(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> dict:
    """Run the tool's main() with output redirected into tmp_path.

    ``LOCK_FILE`` is intentionally NOT patched: the tool must consume the
    repo's real ``custom_nodes.lock`` end to end.
    """
    ready_dir = tmp_path / "ready_templates"
    ready_dir.mkdir(parents=True)
    (ready_dir / "sample.py").write_text(_FIXTURE_TEMPLATE, encoding="utf-8")
    cache_dir = tmp_path / "cache"
    monkeypatch.setattr(audit, "READY_DIR", ready_dir)
    monkeypatch.setattr(audit, "CACHE_DIR", cache_dir)
    monkeypatch.setattr(audit, "INVENTORY_PATH", cache_dir / "class_inventory.json")

    assert audit.main() == 0

    inventory_path = cache_dir / "class_inventory.json"
    assert inventory_path.exists()
    return json.loads(inventory_path.read_text(encoding="utf-8"))


def test_main_runs_end_to_end_on_repo_lock(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The tool audits the repo's real lock and emits the expected shape."""
    inventory = _run_audit(tmp_path, monkeypatch)

    assert set(inventory) == {
        "typed_wrappers",
        "fallback_helpers",
        "schema_missing",
        "stats",
    }
    stats = inventory["stats"]
    assert set(stats) == {"total_classes", "total_files", "total_refs"}
    assert stats == {"total_classes": 3, "total_files": 1, "total_refs": 3}

    # Pack class_sets read via read_lockfile drive the pack attribution:
    # the attribution must match whatever the shared reader reports today.
    expected_pack = next(
        (
            name
            for name, classes in audit.parse_custom_nodes_lock(audit.LOCK_FILE).items()
            if "DualCLIPLoaderGGUF" in classes
        ),
        None,
    )
    gguf_entry = inventory["typed_wrappers"]["DualCLIPLoaderGGUF"]
    assert gguf_entry["pack"] == expected_pack
    assert gguf_entry["is_core"] is (expected_pack is None)
    assert inventory["typed_wrappers"]["KSampler"]["pack"] is None
    assert inventory["typed_wrappers"]["KSampler"]["is_core"] is True
    assert inventory["fallback_helpers"]["Note"]["class_type"] == "Note"

    # Every referenced class_type lands in exactly one bucket; the
    # schema_missing bucket is never populated by the current classifier.
    classified = len(inventory["typed_wrappers"]) + len(inventory["fallback_helpers"])
    assert classified == stats["total_classes"] == 3
    assert inventory["schema_missing"] == {}


def test_parse_custom_nodes_lock_maps_read_lockfile_entries(tmp_path: Path) -> None:
    """parse_custom_nodes_lock maps the shared reader's LockEntry shape."""
    lock = tmp_path / "custom_nodes.lock"
    lock.write_text(
        "# Generated by vibecomfy nodes lock.\n"
        "\n"
        "[nodepacks.Alpha]\n"
        'name = "Alpha"\n'
        'slug = "Alpha"\n'
        'source = "git"\n'
        'commit = "abc123"\n'
        'git_commit_sha = "abc123"\n'
        'url = "https://example.test/alpha.git"\n'
        'class_set = ["Beta", "AlphaNode"]\n'
        "\n"
        "[nodepacks.Bare]\n"
        'name = "Bare"\n'
        'slug = "Bare"\n'
        'source = "git"\n'
        'commit = "def456"\n'
        'git_commit_sha = "def456"\n'
        'url = "https://example.test/bare.git"\n',
        encoding="utf-8",
    )

    assert audit.parse_custom_nodes_lock(lock) == {
        "Alpha": {"AlphaNode", "Beta"},
        "Bare": set(),
    }


def test_tool_has_no_hand_parsed_toml() -> None:
    """The tool must delegate lockfile parsing to read_lockfile (no tomllib)."""
    source = TOOL_PATH.read_text(encoding="utf-8")
    assert "tomllib" not in source
    assert "read_lockfile" in source
