from __future__ import annotations

from pathlib import Path

import pytest

from vibecomfy.node_packs_lockfile import LockEntry


@pytest.fixture(autouse=True)
def _clear_node_pack_cache():
    import vibecomfy.node_packs as node_packs

    node_packs.clear_known_node_packs_cache()
    yield
    node_packs.clear_known_node_packs_cache()


def test_resolve_node_packs_uses_rich_lock_class_sets(monkeypatch) -> None:
    import vibecomfy.node_packs as node_packs

    def fake_read_lockfile(path: Path = Path("custom_nodes.lock")) -> list[LockEntry]:
        return [
            LockEntry(
                name="ComfyUI-RichPack",
                slug="comfyui-rich-pack",
                source="comfy-registry",
                version="1.0.0",
                commit="abc123",
                url="https://example.test/rich.git",
                class_set=("RichNodeB", "RichNodeA"),
                pip_packages=("example-extra",),
                schema_hash="feedface",
            )
        ]

    monkeypatch.setattr(node_packs, "read_lockfile", fake_read_lockfile)

    packs = node_packs.resolve_node_packs({"RichNodeA"})

    assert [(pack.name, pack.repo, sorted(pack.classes), pack.pip_packages, pack.class_schema_sha256) for pack in packs] == [
        (
            "ComfyUI-RichPack",
            "https://example.test/rich.git",
            ["RichNodeA", "RichNodeB"],
            ("example-extra",),
            "feedface",
        )
    ]
    assert node_packs.unresolved_class_types({"RichNodeA", "MissingNode"}) == ["MissingNode"]


def test_rich_lock_overrides_static_seed_pack_by_name(monkeypatch) -> None:
    import vibecomfy.node_packs as node_packs

    def fake_read_lockfile(path: Path = Path("custom_nodes.lock")) -> list[LockEntry]:
        return [
            LockEntry(
                name="ComfyUI-KJNodes",
                git_commit_sha="abc123",
                url="https://example.test/kj.git",
                class_set=("OnlyLockedKJNode",),
            )
        ]

    monkeypatch.setattr(node_packs, "read_lockfile", fake_read_lockfile)

    assert [pack.name for pack in node_packs.resolve_node_packs({"OnlyLockedKJNode"})] == ["ComfyUI-KJNodes"]
    assert node_packs.resolve_node_packs({"ImageResizeKJv2"}) == []


def test_static_seed_packs_remain_bootstrap_fallback(monkeypatch) -> None:
    import vibecomfy.node_packs as node_packs

    monkeypatch.setattr(node_packs, "read_lockfile", lambda path=Path("custom_nodes.lock"): [])

    packs = node_packs.resolve_node_packs({"ImageResizeKJv2"})

    assert [pack.name for pack in packs] == ["ComfyUI-KJNodes"]
    assert node_packs.unresolved_class_types({"ImageResizeKJv2"}) == []


def test_lockfile_mutation_invalidates_cache_in_same_interpreter(tmp_path: Path) -> None:
    """Writing a new ``custom_nodes.lock`` changes the return value of
    ``get_known_node_packs()`` without a process restart.  ``resolve_node_packs``
    is verified by inspecting the returned packs directly (it uses the default
    lockfile path, so the custom-path proof lives on ``get_known_node_packs``)."""
    import time

    import vibecomfy.node_packs as node_packs

    lock_path = tmp_path / "custom_nodes.lock"

    # --- Phase 1: write initial lock file with one pack ---
    lock_path.write_text(
        """\
# Generated by vibecomfy nodes lock.

[nodepacks.TestPackOne]
name = "TestPackOne"
slug = "TestPackOne"
source = "git"
version = "unknown"
commit = "abc123"
git_commit_sha = "abc123"
url = "https://example.test/one.git"
class_set = ["TestNodeA", "TestNodeB"]
""",
        encoding="utf-8",
    )

    packs_one = node_packs.get_known_node_packs(lockfile_path=lock_path)
    names_one = {pack.name for pack in packs_one}
    assert "TestPackOne" in names_one

    # resolve_node_packs uses the default lockfile path; verify pack resolution
    # by inspecting the packs returned from get_known_node_packs directly.
    pack_one = [p for p in packs_one if p.name == "TestPackOne"]
    assert len(pack_one) == 1
    assert "TestNodeA" in pack_one[0].classes
    assert "TestNodeB" in pack_one[0].classes
    assert pack_one[0].repo == "https://example.test/one.git"

    # Also confirm resolve_node_packs picks up packs from the dedicated path.
    packs_from_resolve = node_packs.resolve_node_packs({"TestNodeA", "TestNodeB"})
    assert "TestPackOne" not in {pack.name for pack in packs_from_resolve}, (
        "resolve_node_packs uses the default lockfile, not the temp one"
    )

    # --- Phase 2: overwrite with a different pack ---
    # Small delay to guarantee mtime_ns tick on coarse-resolution filesystems.
    time.sleep(0.01)
    lock_path.write_text(
        """\
# Generated by vibecomfy nodes lock.

[nodepacks.TestPackTwo]
name = "TestPackTwo"
slug = "TestPackTwo"
source = "git"
version = "unknown"
commit = "def456"
git_commit_sha = "def456"
url = "https://example.test/two.git"
class_set = ["TestNodeC"]
""",
        encoding="utf-8",
    )

    packs_two = node_packs.get_known_node_packs(lockfile_path=lock_path)
    names_two = {pack.name for pack in packs_two}
    assert "TestPackOne" not in names_two, (
        "Old pack should disappear after lock file overwrite"
    )
    assert "TestPackTwo" in names_two

    pack_two = [p for p in packs_two if p.name == "TestPackTwo"]
    assert len(pack_two) == 1
    assert "TestNodeC" in pack_two[0].classes
    assert pack_two[0].repo == "https://example.test/two.git"

    # The old class is no longer in the catalog for this lockfile.
    all_classes_two = {cls for p in packs_two for cls in p.classes}
    assert "TestNodeA" not in all_classes_two
