from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Mapping

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 compatibility
    import tomli as tomllib  # type: ignore[no-redef]


@dataclass
class LockEntry:
    name: str
    git_commit_sha: str | None = None
    url: str | None = None
    slug: str | None = None
    source: str = "git"
    version: str | None = None
    commit: str | None = None
    path: str | None = None
    schema_hash: str | None = None
    class_set: tuple[str, ...] = ()
    last_seen_at: str | None = None
    pip_packages: tuple[str, ...] = ()
    semantic_label: str | None = None
    source_sha256: dict[str, str] = field(default_factory=dict)
    class_schema_sha256: str | None = None

    def __post_init__(self) -> None:
        if self.slug is None:
            self.slug = self.name
        if self.commit is None and self.git_commit_sha is not None:
            self.commit = self.git_commit_sha
        if self.git_commit_sha is None and self.commit is not None:
            self.git_commit_sha = self.commit
        if self.schema_hash is None and self.class_schema_sha256 is not None:
            self.schema_hash = self.class_schema_sha256
        if self.class_schema_sha256 is None and self.schema_hash is not None:
            self.class_schema_sha256 = self.schema_hash
        self.class_set = tuple(sorted({str(item) for item in self.class_set}))
        self.pip_packages = tuple(sorted({str(item) for item in self.pip_packages}))


def read_lockfile(path: Path = Path("custom_nodes.lock")) -> list[LockEntry]:
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    stripped = text.strip()
    if not stripped:
        return []
    first_content = next(
        (line.strip() for line in stripped.splitlines() if line.strip() and not line.lstrip().startswith("#")),
        "",
    )
    if first_content.startswith("[") or first_content.startswith("=") or "=" in first_content:
        return _read_toml_lockfile(stripped)
    return _read_legacy_lockfile(stripped)


def _any_entry_has_rich_data(entries: list[LockEntry]) -> bool:
    """Return True if any entry carries data requiring TOML persistence."""
    return any(
        entry.source_sha256
        or entry.class_schema_sha256 is not None
        or entry.schema_hash is not None
        or entry.semantic_label is not None
        or entry.slug != entry.name
        or entry.source != "git"
        or entry.version is not None
        or entry.path is not None
        or bool(entry.class_set)
        or entry.last_seen_at is not None
        or bool(entry.pip_packages)
        for entry in entries
    )


def write_lockfile(entries: list[LockEntry], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    sorted_entries = sorted(entries, key=lambda item: item.name)

    if _any_entry_has_rich_data(entries):
        _write_toml_lockfile(sorted_entries, path)
    else:
        _write_legacy_lockfile(sorted_entries, path)


def _write_legacy_lockfile(entries: list[LockEntry], path: Path) -> None:
    lines = ["# Generated by vibecomfy nodes lock."]
    for entry in entries:
        if entry.git_commit_sha is None or entry.url is None:
            raise ValueError(f"Legacy lock entry {entry.name!r} requires git_commit_sha and url")
        lines.append(f"{entry.name} {entry.git_commit_sha} {entry.url}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_toml_lockfile(entries: list[LockEntry], path: Path) -> None:
    lines = ["# Generated by vibecomfy nodes lock."]
    for entry in entries:
        lines.append("")
        lines.append(f"[nodepacks.{entry.name}]")
        lines.append(f"name = {_toml_quote(entry.name)}")
        if entry.slug is not None:
            lines.append(f"slug = {_toml_quote(entry.slug)}")
        lines.append(f"source = {_toml_quote(entry.source)}")
        if entry.version is not None:
            lines.append(f"version = {_toml_quote(entry.version)}")
        if entry.commit is not None:
            lines.append(f"commit = {_toml_quote(entry.commit)}")
        if entry.git_commit_sha is not None:
            lines.append(f"git_commit_sha = {_toml_quote(entry.git_commit_sha)}")
        if entry.url is not None:
            lines.append(f"url = {_toml_quote(entry.url)}")
        if entry.path is not None:
            lines.append(f"path = {_toml_quote(entry.path)}")
        if entry.schema_hash is not None:
            lines.append(f"schema_hash = {_toml_quote(entry.schema_hash)}")
        if entry.semantic_label is not None:
            lines.append(f"semantic_label = {_toml_quote(entry.semantic_label)}")
        if entry.class_schema_sha256 is not None:
            lines.append(f"class_schema_sha256 = {_toml_quote(entry.class_schema_sha256)}")
        if entry.last_seen_at is not None:
            lines.append(f"last_seen_at = {_toml_quote(entry.last_seen_at)}")
        if entry.class_set:
            lines.append(f"class_set = {_toml_array(entry.class_set)}")
        if entry.pip_packages:
            lines.append(f"pip_packages = {_toml_array(entry.pip_packages)}")
        if entry.source_sha256:
            lines.append(f"[nodepacks.{entry.name}.source_sha256]")
            for key, value in sorted(entry.source_sha256.items()):
                lines.append(f"{_toml_quote(key)} = {_toml_quote(value)}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def upsert_lockfile_entry(entry: LockEntry, path: Path = Path("custom_nodes.lock")) -> None:
    entries = read_lockfile(path)
    for index, existing in enumerate(entries):
        if existing.name == entry.name:
            # Preserve class_schema_sha256 from the existing entry when the
            # incoming entry doesn't carry one (e.g. install/ensure paths).
            if entry.class_schema_sha256 is None and existing.class_schema_sha256 is not None:
                entry = LockEntry(
                    name=entry.name,
                    git_commit_sha=entry.git_commit_sha,
                    url=entry.url,
                    slug=entry.slug,
                    source=entry.source,
                    version=entry.version,
                    commit=entry.commit,
                    path=entry.path,
                    schema_hash=entry.schema_hash,
                    class_set=entry.class_set,
                    last_seen_at=entry.last_seen_at,
                    pip_packages=entry.pip_packages,
                    semantic_label=entry.semantic_label,
                    source_sha256=entry.source_sha256,
                    class_schema_sha256=existing.class_schema_sha256,
                )
            entries[index] = entry
            break
    else:
        entries.append(entry)
    write_lockfile(entries, path)


def _read_legacy_lockfile(text: str) -> list[LockEntry]:
    entries: list[LockEntry] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split()
        if len(parts) != 3:
            raise ValueError(f"Invalid legacy custom_nodes.lock line {lineno}: expected 3 whitespace tokens")
        name, git_commit_sha, url = parts
        entries.append(LockEntry(name=name, git_commit_sha=git_commit_sha, url=url))
    return entries


def _read_toml_lockfile(text: str) -> list[LockEntry]:
    data = tomllib.loads(text)
    entries: list[LockEntry] = []
    if isinstance(data.get("entries"), list):
        for raw in data["entries"]:
            if isinstance(raw, dict):
                entries.append(_entry_from_mapping(raw.get("name"), raw))
        return entries
    nodepacks = data.get("nodepacks")
    if isinstance(nodepacks, dict):
        for name, raw in nodepacks.items():
            if isinstance(raw, dict):
                entries.append(_entry_from_mapping(name, raw))
        return entries
    for name, raw in data.items():
        if isinstance(raw, dict) and ("git_commit_sha" in raw or "git_sha" in raw):
            entries.append(_entry_from_mapping(name, raw))
    return entries


def _entry_from_mapping(name: Any, raw: dict[str, Any]) -> LockEntry:
    entry_name = str(raw.get("name") or name)
    source = str(raw.get("source") or "git")
    git_commit_sha = raw.get("git_commit_sha", raw.get("git_sha", raw.get("commit")))
    commit = raw.get("commit", git_commit_sha)
    url = raw.get("url")
    path = raw.get("path")
    if source == "git" and git_commit_sha is None:
        raise ValueError(f"Lock entry {entry_name!r} is missing git_commit_sha")
    if source == "git" and url is None:
        raise ValueError(f"Lock entry {entry_name!r} is missing url")
    if source == "local" and path is None:
        raise ValueError(f"Lock entry {entry_name!r} is missing path")
    source_sha256 = raw.get("source_sha256") or {}
    if not isinstance(source_sha256, dict):
        raise ValueError(f"Lock entry {entry_name!r} source_sha256 must be a table")
    class_set = _string_tuple(raw.get("class_set"), "class_set", entry_name)
    pip_packages = _string_tuple(raw.get("pip_packages"), "pip_packages", entry_name)
    class_schema_sha256 = raw.get("class_schema_sha256")
    schema_hash = raw.get("schema_hash", class_schema_sha256)
    semantic_label = raw.get("semantic_label")
    return LockEntry(
        name=entry_name,
        git_commit_sha=str(git_commit_sha) if git_commit_sha is not None else None,
        url=str(url) if url is not None else None,
        slug=str(raw.get("slug") or entry_name),
        source=source,
        version=str(raw["version"]) if raw.get("version") is not None else None,
        commit=str(commit) if commit is not None else None,
        path=str(path) if path is not None else None,
        schema_hash=str(schema_hash) if schema_hash is not None else None,
        class_set=class_set,
        last_seen_at=str(raw["last_seen_at"]) if raw.get("last_seen_at") is not None else None,
        pip_packages=pip_packages,
        semantic_label=str(semantic_label) if semantic_label is not None else None,
        source_sha256={str(key): str(value) for key, value in source_sha256.items()},
        class_schema_sha256=str(class_schema_sha256) if class_schema_sha256 is not None else None,
    )


def _string_tuple(value: Any, field_name: str, entry_name: str) -> tuple[str, ...]:
    if value is None:
        return ()
    if not isinstance(value, list):
        raise ValueError(f"Lock entry {entry_name!r} {field_name} must be an array")
    return tuple(sorted(str(item) for item in value))


def _toml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_array(values: tuple[str, ...]) -> str:
    return "[" + ", ".join(_toml_quote(value) for value in sorted(values)) + "]"


def canonical_class_schema_projection(class_type: str, schema: Mapping[str, Any]) -> dict[str, Any]:
    inputs = schema.get("input") if isinstance(schema.get("input"), Mapping) else schema.get("inputs")
    inputs = inputs if isinstance(inputs, Mapping) else {}
    required = _canonical_input_group(schema.get("required", inputs.get("required")))
    optional = _canonical_input_group(schema.get("optional", inputs.get("optional")))
    hidden = _canonical_input_group(schema.get("hidden", inputs.get("hidden")))
    return {
        "class_type": class_type,
        "required": required,
        "optional": optional,
        "hidden": hidden,
        "outputs": _jsonable(schema.get("outputs", schema.get("output", []))),
        "output_names": _jsonable(schema.get("output_names", schema.get("output_name", []))),
        "input_order": _jsonable(schema.get("input_order", _input_order(required, optional, hidden))),
        "widget_defaults": _jsonable(schema.get("widget_defaults", _widget_defaults(required, optional, hidden))),
    }


def canonical_pack_schema_projection(class_schemas: Mapping[str, Mapping[str, Any]]) -> list[dict[str, Any]]:
    return [
        canonical_class_schema_projection(class_type, class_schemas[class_type])
        for class_type in sorted(class_schemas)
    ]


def compute_schema_hash(class_schemas: Mapping[str, Mapping[str, Any]]) -> str:
    payload = json.dumps(
        canonical_pack_schema_projection(class_schemas),
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    )
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _canonical_input_group(value: Any) -> dict[str, Any]:
    if not isinstance(value, Mapping):
        return {}
    return {str(key): _jsonable(item) for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))}


def _input_order(*groups: Mapping[str, Any]) -> list[str]:
    ordered: list[str] = []
    for group in groups:
        ordered.extend(str(key) for key in group)
    return ordered


def _widget_defaults(*groups: Mapping[str, Any]) -> dict[str, Any]:
    defaults: dict[str, Any] = {}
    for group in groups:
        for key, value in group.items():
            default = _extract_default(value)
            if default is not None:
                defaults[str(key)] = default
    return defaults


def _extract_default(value: Any) -> Any:
    if isinstance(value, (list, tuple)) and len(value) > 1 and isinstance(value[1], Mapping) and "default" in value[1]:
        return _jsonable(value[1]["default"])
    if isinstance(value, Mapping) and "default" in value:
        return _jsonable(value["default"])
    return None


def _jsonable(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))}
    if isinstance(value, (list, tuple)):
        return [_jsonable(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)
