from __future__ import annotations

from vibecomfy.porting import slot_codec  # noqa: F401 — public M1 submodule
from vibecomfy.porting.assets import AssetAnalysis
from vibecomfy.porting.emitter import (
    EmissionDiagnostic,
    InputSignatureField,
    NodeSignatureRow,
    OutputSignatureField,
    READABILITY_WARNING_AVOIDABLE_POSITIONAL_OUTPUT,
    READABILITY_WARNING_CODES,
    READABILITY_WARNING_HIDDEN_MODEL_FILENAME,
    READABILITY_WARNING_OUTPUT_NAME_AMBIGUITY,
    READABILITY_WARNING_SCHEMA_BACKED_WIDGET_ALIAS_NOT_RESOLVED,
    emit_agent_edit_python,
    emit_available_node_signatures,
    format_signature_rows,
)
from vibecomfy.porting.edit_session import (
    BatchResult,
    CompactDiagnostic,
    DoneResult,
    EditSession,
    InputSlotInfo,
    NodeDescriptor,
    OutputSlotInfo,
    StatementResult,
)
from vibecomfy.porting.edit_types import FieldChange
from vibecomfy.porting.parity import (
    class_type_counter,
    compile_equivalent,
    topology_counter,
    widget_value_counter,
)
from vibecomfy.porting.provenance import (
    ProvenanceConflict,
    ProvenanceRecord,
    ProvenanceReport,
    ProvenanceRequirement,
    ProvenanceVersionPin,
    ProvenanceWarning,
    extract_provenance,
)
from vibecomfy.porting.report import (
    AssetCandidate,
    AssetCheckResult,
    NodePackSuggestion,
    PortArtifact,
    PortIssue,
    PortReport,
)
from vibecomfy.porting.slot_codec import (
    build_reverse_map,
    encode_slot_names,
    to_python_identifier,
    to_raw_name,
)
from vibecomfy.porting.strict_ready import (
    HIDDEN_MODEL_FILENAME,
    OPAQUE_COMPONENT_NODE_CLASS,
    STRICT_READY_BROKEN_PUBLIC_INPUT,
    STRICT_READY_BUILD_FAILED,
    STRICT_READY_COMPILE_FAILED,
    STRICT_READY_LOAD_FAILED,
    STRICT_READY_MISSING_OUTPUT_CONTRACT,
    STRICT_READY_MISSING_PUBLIC_INPUT,
    STRICT_READY_UNNAMED_OUTPUT_CONTRACT,
    STRICT_READY_UNRESOLVED_WIDGETS,
    STRICT_READY_VIOLATION_CODES,
    StrictReadyContext,
    StrictReadyException,
    apply_strict_ready_exceptions,
    load_strict_ready_exceptions,
    validate_strict_ready_workflow,
)

__all__ = [
    "AssetAnalysis",
    "AssetCandidate",
    "AssetCheckResult",
    "BatchResult",
    "build_reverse_map",
    "class_type_counter",
    "CompactDiagnostic",
    "compile_equivalent",
    "DoneResult",
    "EditSession",
    "EmissionDiagnostic",
    "FieldChange",
    "encode_slot_names",
    "emit_agent_edit_python",
    "emit_available_node_signatures",
    "format_signature_rows",
    "InputSignatureField",
    "InputSlotInfo",
    "NodeDescriptor",
    "NodePackSuggestion",
    "NodeSignatureRow",
    "OutputSlotInfo",
    "OutputSignatureField",
    "PortArtifact",
    "PortIssue",
    "ProvenanceConflict",
    "ProvenanceRecord",
    "ProvenanceReport",
    "ProvenanceRequirement",
    "ProvenanceVersionPin",
    "ProvenanceWarning",
    "PortReport",
    "READABILITY_WARNING_AVOIDABLE_POSITIONAL_OUTPUT",
    "READABILITY_WARNING_CODES",
    "READABILITY_WARNING_HIDDEN_MODEL_FILENAME",
    "READABILITY_WARNING_OUTPUT_NAME_AMBIGUITY",
    "READABILITY_WARNING_SCHEMA_BACKED_WIDGET_ALIAS_NOT_RESOLVED",
    "HIDDEN_MODEL_FILENAME",
    "OPAQUE_COMPONENT_NODE_CLASS",
    "STRICT_READY_BROKEN_PUBLIC_INPUT",
    "STRICT_READY_BUILD_FAILED",
    "STRICT_READY_COMPILE_FAILED",
    "STRICT_READY_LOAD_FAILED",
    "STRICT_READY_MISSING_OUTPUT_CONTRACT",
    "STRICT_READY_MISSING_PUBLIC_INPUT",
    "STRICT_READY_UNNAMED_OUTPUT_CONTRACT",
    "STRICT_READY_UNRESOLVED_WIDGETS",
    "STRICT_READY_VIOLATION_CODES",
    "StrictReadyContext",
    "StrictReadyException",
    "apply_strict_ready_exceptions",
    "load_strict_ready_exceptions",
    "slot_codec",
    "StatementResult",
    "to_python_identifier",
    "to_raw_name",
    "topology_counter",
    "extract_provenance",
    "validate_strict_ready_workflow",
    "widget_value_counter",
]
