"""Widget-only positional schema shared by porting and conversion tools.

Entries map a ComfyUI class type to ordered `widgets_values` API input
names. Link-only sockets such as IMAGE, MODEL, CLIP, VAE, and LATENT are
intentionally excluded so positional widgets cannot be shifted by object_info
link inputs.
"""

from __future__ import annotations

WIDGET_SEMANTIC_NAMES: dict[str, dict[str, str]] = {
    "PrimitiveInt": {"widget_0": "value", "widget_1": "control_after_generate"},
    "PrimitiveString": {"widget_0": "value"},
    "PrimitiveStringMultiline": {"widget_0": "value"},
    "PrimitiveFloat": {"widget_0": "value", "widget_1": "control_after_generate"},
    "PrimitiveBoolean": {"widget_0": "value"},
}

WIDGET_SCHEMA: dict[str, list[str | None]] = {
    "BasicScheduler": ["scheduler", "steps", "denoise"],
    "CFGGuider": ["cfg"],
    "CheckpointLoaderSimple": ["ckpt_name"],
    "CLIPLoader": ["clip_name", "type", "device"],
    "CLIPTextEncode": ["text"],
    "CLIPTextEncodeFlux": ["clip_l", "t5xxl", "guidance"],
    "CLIPTextEncodeSD3": ["clip_l", "clip_g", "t5xxl", "empty_padding"],
    "ConditioningSetTimestepRange": ["start", "end"],
    "CreateVideo": ["fps"],
    "DualCLIPLoader": ["clip_name1", "clip_name2", "type", "device"],
    "DualCLIPLoaderGGUF": ["clip_name1", "clip_name2", "type"],
    "EmptyFlux2LatentImage": ["width", "height", "batch_size"],
    "EmptyHunyuanLatentVideo": ["width", "height", "length", "batch_size"],
    "EmptyLTXVLatentVideo": ["width", "height", "length", "batch_size"],
    "EmptySD3LatentImage": ["width", "height", "batch_size"],
    "FluxGuidance": ["guidance"],
    "Flux2Scheduler": ["steps", "width", "height"],
    "GetImageSize": [],
    "ImageResize": ["resize_mode", "resolutions", "interpolation", "aspect_ratio_tolerance"],
    "ImageScale": ["upscale_method", "width", "height", "crop"],
    "ImageScaleBy": ["upscale_method", "scale_by"],
    "ImageScaleToTotalPixels": ["upscale_method", "megapixels", "resolution_steps"],
    "KSampler": ["seed", None, "steps", "cfg", "sampler_name", "scheduler", "denoise"],
    "KSamplerAdvanced": [
        "add_noise",
        "noise_seed",
        None,
        "steps",
        "cfg",
        "sampler_name",
        "scheduler",
        "start_at_step",
        "end_at_step",
        "return_with_leftover_noise",
    ],
    "KSamplerSelect": ["sampler_name"],
    "LoadAudio": ["audio"],
    "LoadImage": ["image", None],
    "LoraLoaderModelOnly": ["lora_name", "strength_model"],
    "LTX2AttentionTunerPatch": [
        "blocks",
        "video_scale",
        "audio_scale",
        "video_to_audio_scale",
        "audio_to_video_scale",
        "triton_kernels",
    ],
    "LTX2MemoryEfficientSageAttentionPatch": ["triton_kernels"],
    "LTX2_NAG": ["nag_scale", "nag_alpha", "nag_tau", None],
    "LTX2SamplingPreviewOverride": ["preview_rate"],
    "LTXICLoRALoaderModelOnly": ["lora_name", "strength_model"],
    "LTXAddVideoICLoRAGuide": [
        "frame_idx",
        "strength",
        "crop",
        "use_tiled_encode",
        None,
        "tile_size",
        "tile_overlap",
    ],
    "LTXVConditioning": ["frame_rate"],
    "LTXVEmptyLatentAudio": ["frames_number", "frame_rate", "batch_size"],
    "LTXVAddGuide": ["frame_idx", "strength"],
    "LTXVChunkFeedForward": ["chunks", "dim_threshold"],
    "LTXVImgToVideoConditionOnly": ["strength", "bypass"],
    "LTXAVTextEncoderLoader": ["text_encoder", "ckpt_name", "device"],
    "LTXVPreprocess": ["img_compression"],
    "LTXFloatToInt": ["rounding"],
    "LTXVScheduler": ["steps", "max_shift", "base_shift", "stretch", "terminal"],
    "LTXVTiledVAEDecode": ["horizontal_tiles", "vertical_tiles", "overlap", "last_frame_fix", None, None],
    "LatentUpscaleModelLoader": ["model_name"],
    "ManualSigmas": ["sigmas"],
    "ModelSamplingAuraFlow": ["shift"],
    "ModelSamplingFlux": ["max_shift", "base_shift", "width", "height"],
    "ModelSamplingSD3": ["shift"],
    "PrimitiveBoolean": ["value"],
    "PrimitiveFloat": ["value"],
    "PrimitiveInt": ["value"],
    "PrimitiveString": ["value"],
    "PrimitiveStringMultiline": ["value"],
    "PathchSageAttentionKJ": ["sage_attention", "allow_compile"],
    "Power Lora Loader (rgthree)": [None, None, None, None],
    "RandomNoise": ["noise_seed", "control_after_generate"],
    "ResizeImagesByLongerEdge": ["longer_edge"],
    "SamplerCustomAdvanced": [],
    "SaveAudio": ["filename_prefix"],
    "SaveAudioMP3": ["filename_prefix", "quality"],
    "SaveImage": ["filename_prefix"],
    "SaveVideo": ["filename_prefix", "format", "codec"],
    "SimpleCalculatorKJ": ["expression"],
    "TextEncodeAceStepAudio1.5": [
        "tags",
        "lyrics",
        "seed",
        None,
        "duration",
        "bpm",
        "timesignature",
        "language",
        "keyscale",
        "generate_audio_codes",
        "cfg_scale",
        "temperature",
        "top_p",
        "top_k",
        "min_p",
    ],
    "TextEncodeQwenImageEdit": ["prompt"],
    "TripleCLIPLoader": ["clip_name1", "clip_name2", "clip_name3"],
    "UNETLoader": ["unet_name", "weight_dtype"],
    "UnetLoaderGGUF": ["unet_name"],
    "VAEDecode": [],
    "VAEDecodeTiled": ["tile_size", "overlap", "temporal_size", "temporal_overlap"],
    "VAEEncode": [],
    "VAELoader": ["vae_name"],
    "VAELoaderKJ": ["vae_name", "device", "weight_dtype"],
    "LoadWanVideoT5TextEncoder": ["model_name", "precision", "load_device", "quantization"],
    "WanVideoTextEncode": ["positive_prompt", "negative_prompt", "force_offload", "use_disk_cache", "device"],
    "WanVideoTextEncodeCached": [
        "model_name",
        "precision",
        "positive_prompt",
        "negative_prompt",
        "quantization",
        "use_disk_cache",
        "device",
    ],
    "CLIPVisionLoader": ["clip_name"],
    "WanVideoModelLoader": ["model", "base_precision", "quantization", "load_device", "attention_mode", "rms_norm_function"],
    "WanVideoBlockSwap": [
        "blocks_to_swap",
        "offload_img_emb",
        "offload_txt_emb",
        "use_non_blocking",
        "vace_blocks_to_swap",
        "prefetch_blocks",
        "block_swap_debug",
    ],
    "WanVideoTorchCompileSettings": [
        "backend",
        "fullgraph",
        "mode",
        "dynamic",
        "dynamo_cache_size_limit",
        "compile_transformer_blocks_only",
        "dynamo_recompile_limit",
        "force_parameter_static_shapes",
        "allow_unmerged_lora_compile",
    ],
    "WanVideoLoraSelect": ["lora", "strength", "low_mem_load", "merge_loras"],
    "WanVideoLoraSelectMulti": [
        "lora_0",
        "strength_0",
        "lora_1",
        "strength_1",
        "lora_2",
        "strength_2",
        "lora_3",
        "strength_3",
        "lora_4",
        "strength_4",
        "low_mem_load",
        "merge_loras",
    ],
    "WanVideoImageToVideoEncode": [
        "width",
        "height",
        "num_frames",
        "noise_aug_strength",
        "start_latent_strength",
        "end_latent_strength",
        "force_offload",
        "tiled_vae",
        "fun_or_fl2v_model",
    ],
    "WanVideoVAELoader": ["model_name", "precision"],
    "WanVideoDecode": ["enable_vae_tiling", "tile_x", "tile_y", "tile_stride_x", "tile_stride_y", "normalization"],
    "WanVideoSampler": [
        "steps",
        "cfg",
        "shift",
        "seed",
        None,
        "force_offload",
        "scheduler",
        "riflex_freq_index",
        "denoise_strength",
        "batched_cfg",
        "rope_function",
        "start_step",
        "end_step",
        "add_noise_to_samples",
    ],
    "CreateCFGScheduleFloatList": [
        "steps",
        "cfg_scale_start",
        "cfg_scale_end",
        "interpolation",
        "start_percent",
        "end_percent",
    ],
    "WanVideoAnimateEmbeds": [
        "width",
        "height",
        "num_frames",
        "force_offload",
        "frame_window_size",
        "colormatch",
        "face_strength",
        "pose_strength",
        "unused_8",
    ],
    "WanVideoClipVisionEncode": [
        "strength_1",
        "strength_2",
        "crop",
        "combine_embeds",
        "force_offload",
        "tiles",
        "ratio",
    ],
    "WanVideoContextOptions": [
        "context_schedule",
        "context_frames",
        "context_stride",
        "context_overlap",
        "freenoise",
        "verbose",
        "fuse_method",
    ],
    "ImageResizeKJv2": [
        "width",
        "height",
        "upscale_method",
        "keep_proportion",
        "pad_color",
        "crop_position",
        "divisible_by",
        "device",
        None,
    ],
    "INTConstant": ["value"],
    "FloatConstant": ["value"],
    "ImageConcatMulti": ["inputcount", "direction", "match_image_size", "unused_3"],
    "BlockifyMask": ["block_size"],
    "CannyEdgePreprocessor": ["low_threshold", "high_threshold", "resolution"],
    "DrawMaskOnImage": ["color"],
    "GrowMask": ["expand", "tapered_corners"],
    "DWPreprocessor": [
        "detect_hand",
        "detect_body",
        "detect_face",
        "resolution",
        "bbox_detector",
        "pose_estimator",
        "scale_stick_for_xinsr_cn",
    ],
    "PointsEditor": [
        "points_store",
        "coordinates",
        "neg_coordinates",
        "bbox_store",
        "bboxes",
        "bbox_format",
        "width",
        "height",
        "normalize",
    ],
    "CLIPVisionEncode": ["crop"],
    "LoadVideo": ["file", None],
    "PixelPerfectResolution": ["resize_mode"],
    "GrowMaskWithBlur": [
        "expand",
        "incremental_expandrate",
        "tapered_corners",
        "flip_input",
        "blur_radius",
        "lerp_alpha",
        "decay_factor",
        "unused_7",
    ],
    "DownloadAndLoadSAM2Model": ["model", "segmentor", "device", "precision"],
    "Sam2Segmentation": ["keep_model_loaded", "individual_objects"],
    "OnnxDetectionModelLoader": ["vitpose_model", "yolo_model", "onnx_device"],
    "PoseAndFaceDetection": ["width", "height", "face_padding"],
    "DrawViTPose": ["width", "height", "retarget_padding", "body_stick_width", "hand_stick_width", "draw_head"],
    "ResizeImageMaskNode": ["resize_type", None, "scale_method"],
    "VHS_VideoCombine": [
        "frame_rate",
        "loop_count",
        "filename_prefix",
        "format",
        "pingpong",
        "save_output",
    ],
}


def effective_widget_names_for_class(
    class_type: str,
    *,
    allow_object_info_fallback: bool = False,
) -> list[str | None]:
    """Return the ordered widget names for *class_type*.

    Curated ``WIDGET_SCHEMA`` always wins when present.  When no curated
    static entry exists and *allow_object_info_fallback* is ``True``, the
    raw object_info widget order is returned as a fallback.

    … note::
        This helper is narrowly scoped for the v2.1 ``narrate_template.py``
        codemod.  It does **not** replace the direct ``WIDGET_SCHEMA.get(…)``
        lookups used by ``widget_aliases.py``, ``emitter.py``, or ``parity.py``
        — global conversion / emission / parity behaviour is unchanged.
    """
    curated = WIDGET_SCHEMA.get(class_type)
    if curated is not None:
        return list(curated)

    if allow_object_info_fallback:
        # Lazy import to avoid circular dependency at module level
        from vibecomfy.porting.object_info.consume import object_info_widget_order  # noqa: PLC0415

        return list(object_info_widget_order(class_type))

    return []


__all__ = ["WIDGET_SCHEMA", "effective_widget_names_for_class"]
