from __future__ import annotations

from vibecomfy.porting.edit.apply_core import apply_delta, resolve_delta
from vibecomfy.porting.edit.apply_gate import (
    _align_candidate_scope_paths,
    _all_diffs_normalize_allowed,
    _all_diffs_op_allowed,
    _counter_advanced_or_materialized,
    _guard_attribution,
    _guard_counter,
    _guard_node_order,
    _guard_scope_fields,
    _guard_scope_links,
    _guard_subgraph_state,
    _links_by_id,
    _normalize_for_guard,
    _path_is_at_or_below,
    _scope_node_uids,
    _value_diff_paths,
    guard_full_ui,
)
from vibecomfy.porting.edit.apply_links import (
    _build_rewires,
    _build_rewires_for_setnode_gets,
    _clear_input_link_reference,
    _collect_links_for_origin,
    _collect_links_for_target,
    _ensure_input_slot,
    _ensure_output_link_reference,
    _helper_broadcast_name,
    _link_endpoints,
    _link_id,
    _link_ids,
    _link_ids_targeting_input,
    _new_link_for_scope,
    _node_by_id,
    _remove_link_from_scope,
    _remove_node_from_scope,
    _remove_output_link_reference,
    _resolve_getnode_source,
    _resolve_passthrough_source,
    _rewire_link_origin,
    _schema_output_type,
    _scope_uses_dict_links,
    _set_input_link_reference,
    _set_link_origin,
    _sync_scope_counters,
)
from vibecomfy.porting.edit.apply_mutate import (
    _apply_add_node,
    _apply_remove_link,
    _apply_remove_node,
    _apply_resolved_op,
    _apply_set_mode,
    _apply_set_node_field,
    _apply_upsert_link,
    _clear_linked_input_surface,
    _write_widget_value,
)
from vibecomfy.porting.edit.apply_place import (
    _COLLISION_NUDGE_X,
    _COLLISION_NUDGE_Y,
    _GROUP_PAD,
    _MAX_COLLISION_NUDGES,
    _NODE_H_GAP,
    _NODE_V_GAP,
    _anchor_position,
    _between_rects,
    _clamp_position_to_group,
    _default_add_node_position,
    _grow_group_to_fit,
    _group_bounding,
    _group_index_by_title,
    _group_index_for_node,
    _group_index_for_rect,
    _left_of_rect,
    _next_node_order,
    _node_rect,
    _node_size,
    _nudge_to_open_slot,
    _place_add_node,
    _rect_overlaps_any_node,
    _rectangles_overlap,
    _right_of_rect,
    _round_pos,
    _target_group_index,
)
from vibecomfy.porting.edit.apply_resolve import _resolve_op
from vibecomfy.porting.edit.apply_resolve_add import (
    _resolve_add_node,
    _resolve_add_node_anchor,
)
from vibecomfy.porting.edit.apply_resolve_base import (
    _resolve_node,
    _resolve_node_only,
    _resolve_remove_link,
    _resolve_remove_node,
    _resolve_scope,
    _resolve_set_node_field,
    _resolve_source_endpoint,
    _resolve_target_endpoint,
    _resolve_upsert_link,
)
from vibecomfy.porting.edit.apply_slots import (
    _find_named_slot_index,
    _widget_index_for_field,
    _widget_index_from_input_stubs,
    _widget_name_for_input,
    _widget_names_from_input_stubs,
)
from vibecomfy.porting.edit.apply_types import (
    AppliedAddNodeSpec,
    ApplyResult,
    GuardResult,
    ResolveResult,
    ResolvedAddNodeSpec,
    ResolvedFieldRef,
    ResolvedLinkEndpoint,
    ResolvedLinkRewire,
    ResolvedNodeRef,
    ResolvedOp,
    ResolvedRemoveLinkRef,
    ResolvedRemoveNodePlan,
    _RESOLUTION_CODE_REMAP,
    _ctx,
    _endpoint_port_issues,
    _issue,
)
from vibecomfy.porting.edit.apply_values import (
    _NO_MATCH,
    _as_number,
    _coerce_choice_value,
    _matches_primitive_type,
    _primitive_expected_type,
    _validate_literal_value,
)

__all__ = [
    "ApplyResult",
    "ResolvedAddNodeSpec",
    "ResolvedFieldRef",
    "ResolvedLinkEndpoint",
    "ResolvedNodeRef",
    "ResolvedRemoveLinkRef",
    "ResolveResult",
    "apply_delta",
    "resolve_delta",
]
