// agent_edit_response_contract_generated.js — Generated JS contract (snake_case canonical)
//
// AUTO-GENERATED by scripts/generate_agent_contract_js.py.
// Source of truth: vibecomfy/comfy_nodes/agent_contracts.py
//
// Symbols in this module use snake_case as the canonical wire format,
// matching the Python wire format and the lifecycle module's existing output.
// camelCase input acceptance and camelCase output wrapping are layered on top
// by agent_edit_response_contract.js — they are NOT part of this module.
//
// inferLegacyOutcome is explicitly JS-only and outside the single-source schema.

// ── Internal helpers ────────────────────────────────────────────────────────

function isObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function asString(value) {
  return typeof value === "string" ? value : null;
}

// ── Rebaseline recovery (snake_case canonical) ──────────────────────────────

/**
 * Normalize a raw rebaseline-recovery object to the canonical snake_case shape.
 * Fields not present or non-string are set to null.
 *
 * @param {*} recovery - raw recovery value
 * @returns {object|null} canonical snake_case recovery, or null
 */
export function normalizeRebaselineRecovery(recovery) {
  if (!recovery || typeof recovery !== "object") {
    return null;
  }
  return {
    action: asString(recovery.action),
    endpoint: asString(recovery.endpoint),
    reason: asString(recovery.reason),
    last_known_baseline_graph_hash: asString(recovery.last_known_baseline_graph_hash),
    submit_graph_hash: asString(recovery.submit_graph_hash),
    submit_structural_graph_hash: asString(recovery.submit_structural_graph_hash),
    client_graph_hash: asString(recovery.client_graph_hash),
    client_structural_graph_hash: asString(recovery.client_structural_graph_hash),
  };
}

/**
 * Extract a rebaseline-recovery payload from a response object.
 * Searches snake_case paths only:
 *   1. response.rebaseline_recovery (top-level)
 *   2. response.agent_failure_context.issues[*].rebaseline_recovery
 *   3. response.outcome.agent_failure_context.issues[*].rebaseline_recovery
 *   4. response.debug.failure.agent_failure_context.issues[*].rebaseline_recovery
 *
 * camelCase input paths are NOT handled here — see the pre-pass in
 * agent_edit_response_contract.js for camelCase input acceptance.
 *
 * @param {*} response - raw response object
 * @returns {object|null} canonical snake_case recovery, or null
 */
export function extractRebaselineRecovery(response) {
  const topLevel = normalizeRebaselineRecovery(response?.rebaseline_recovery);
  if (topLevel) {
    return topLevel;
  }
  const issueSources = [
    response?.agent_failure_context?.issues,
    response?.outcome?.agent_failure_context?.issues,
    response?.debug?.failure?.agent_failure_context?.issues,
  ];
  for (const issues of issueSources) {
    if (!Array.isArray(issues)) {
      continue;
    }
    for (const issue of issues) {
      const recovery = normalizeRebaselineRecovery(issue?.rebaseline_recovery);
      if (recovery) {
        return recovery;
      }
    }
  }
  return null;
}
