#!/usr/bin/env python3
"""Generate agent_edit_response_contract_generated.js from the Python source of truth.

Source of truth: vibecomfy/comfy_nodes/agent_contracts.py (REBASELINE_RECOVERY_FIELDS)

Produces: vibecomfy/comfy_nodes/web/agent_edit_response_contract_generated.js

Determinism contract:
  - Key ordering follows REBASELINE_RECOVERY_FIELDS tuple order.
  - Double-quoted JS strings throughout.
  - 2-space indentation.
  - Single trailing newline (POSIX).
  - No timestamps, no version hashes, no non-deterministic output.
"""

from __future__ import annotations

import os
import sys


def _ensure_import_path() -> None:
    """Add the repo root to sys.path so we can import vibecomfy."""
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    if repo_root not in sys.path:
        sys.path.insert(0, repo_root)


def _load_fields() -> tuple[str, ...]:
    """Load REBASELINE_RECOVERY_FIELDS from the Python source of truth."""
    from vibecomfy.comfy_nodes.agent_contracts import REBASELINE_RECOVERY_FIELDS

    return REBASELINE_RECOVERY_FIELDS


def _load_constants() -> dict[str, object]:
    """Load shared constants from the Python source of truth."""
    from vibecomfy.comfy_nodes.agent_contracts import (
        FAILURE_HINT_KEYS,
        INTERNAL_TO_PUBLIC_OUTCOME,
        PUBLIC_OUTCOME_KINDS,
    )

    # INTERNAL_TO_PUBLIC_OUTCOME in Python includes all mappings; the JS
    # INTERNAL_OUTCOME_KIND_MAP is intentionally a subset — only the entries
    # that map to "candidate" because those are the only ones the JS dispatch
    # logic queries.
    internal_outcome_kind_entries = [
        (k, v)
        for k, v in INTERNAL_TO_PUBLIC_OUTCOME.items()
        if v == "candidate"
    ]
    return {
        "PUBLIC_OUTCOME_KINDS": tuple(PUBLIC_OUTCOME_KINDS),
        "INTERNAL_OUTCOME_KIND_ENTRIES": tuple(internal_outcome_kind_entries),
        "FAILURE_HINT_KEYS": tuple(FAILURE_HINT_KEYS),
    }


def generate_js(fields: tuple[str, ...]) -> str:
    """Produce the complete JS module source as a string."""
    constants = _load_constants()

    field_js_entries = ",\n".join(
        f"    {f}: asString(recovery.{f})"
        for f in fields
    )

    # The search paths for extractRebaselineRecovery — these are the snake_case
    # dotted paths where a rebaseline_recovery object may nest inside a failure
    # response.  They are NOT derived from REBASELINE_RECOVERY_FIELDS; they are
    # the structural response-paths where the recovery payload lives.
    issue_context_paths = [
        "response?.agent_failure_context?.issues",
        "response?.outcome?.agent_failure_context?.issues",
        "response?.debug?.failure?.agent_failure_context?.issues",
    ]
    issue_context_js = ",\n".join(f"    {path}" for path in issue_context_paths)

    # Serialise the Python constants to JS literals.
    import json

    public_outcome_kinds_js = json.dumps(list(constants["PUBLIC_OUTCOME_KINDS"]), indent=2)
    failure_hint_keys_js = json.dumps(list(constants["FAILURE_HINT_KEYS"]), indent=2)
    internal_kind_entries_js = ",\n".join(
        f'    {json.dumps(k)}: {json.dumps(v)}'
        for k, v in constants["INTERNAL_OUTCOME_KIND_ENTRIES"]
    )

    return f"""\
// agent_edit_response_contract_generated.js — Generated JS contract (snake_case canonical)
//
// AUTO-GENERATED by scripts/generate_agent_contract_js.py.
// Source of truth: vibecomfy/comfy_nodes/agent_contracts.py
//
// Symbols in this module use snake_case as the canonical wire format,
// matching the Python wire format and the lifecycle module's existing output.
// camelCase input acceptance and camelCase output wrapping are layered on top
// by agent_edit_response_contract.js — they are NOT part of this module.
//
// inferLegacyOutcome is explicitly JS-only and outside the single-source schema.

// ── Internal helpers ────────────────────────────────────────────────────────

function isObject(value) {{
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}}

function asString(value) {{
  return typeof value === "string" ? value : null;
}}

// ── Constants (shared, Python-sourced) ──────────────────────────────────────

export const PUBLIC_OUTCOME_KINDS = Object.freeze({public_outcome_kinds_js});

export const INTERNAL_OUTCOME_KIND_MAP = Object.freeze({{
{internal_kind_entries_js},
}});

export const FAILURE_HINT_KEYS = Object.freeze({failure_hint_keys_js});

export const NORMALIZED_RESPONSE_MARKER = "__agentEditResponseNormalized";

// ── Candidate-payload detection ─────────────────────────────────────────────

/**
 * Check whether a raw response contains a candidate payload.
 *
 * candidate_graph is treated as a peer of candidate and graph (rather than
 * nested under .candidate) because it is the canonical snake_case wire
 * container for structured graph data.  This flattening keeps the logic in
 * normalizeCandidateGraph straightforward and avoids a recursive-normalization
 * tangle when a response carries only candidate_graph without a parent
 * candidate envelope.  The decision is deliberate and cross-checked against
 * the Python-side candidate-graph extraction in agent_edit.py.
 *
 * @param {{*}} response - raw response object
 * @returns {{boolean}}
 */
export function responseHasCandidatePayload(response) {{
  if (!isObject(response)) {{
    return false;
  }}
  return isObject(response.candidate)
    || isObject(response.candidate_graph)
    || isObject(response.graph);
}}

// ── Rebaseline recovery (snake_case canonical) ──────────────────────────────

/**
 * Normalize a raw rebaseline-recovery object to the canonical snake_case shape.
 * Fields not present or non-string are set to null.
 *
 * @param {{*}} recovery - raw recovery value
 * @returns {{object|null}} canonical snake_case recovery, or null
 */
export function normalizeRebaselineRecovery(recovery) {{
  if (!recovery || typeof recovery !== "object") {{
    return null;
  }}
  return {{
{field_js_entries},
  }};
}}

/**
 * Extract a rebaseline-recovery payload from a response object.
 * Searches snake_case paths only:
 *   1. response.rebaseline_recovery (top-level)
 *   2. response.agent_failure_context.issues[*].rebaseline_recovery
 *   3. response.outcome.agent_failure_context.issues[*].rebaseline_recovery
 *   4. response.debug.failure.agent_failure_context.issues[*].rebaseline_recovery
 *
 * camelCase input paths are NOT handled here — see the pre-pass in
 * agent_edit_response_contract.js for camelCase input acceptance.
 *
 * @param {{*}} response - raw response object
 * @returns {{object|null}} canonical snake_case recovery, or null
 */
export function extractRebaselineRecovery(response) {{
  const topLevel = normalizeRebaselineRecovery(response?.rebaseline_recovery);
  if (topLevel) {{
    return topLevel;
  }}
  const issueSources = [
{issue_context_js},
  ];
  for (const issues of issueSources) {{
    if (!Array.isArray(issues)) {{
      continue;
    }}
    for (const issue of issues) {{
      const recovery = normalizeRebaselineRecovery(issue?.rebaseline_recovery);
      if (recovery) {{
        return recovery;
      }}
    }}
  }}
  return null;
}}
"""


def main() -> int:
    """Generate and write the JS contract file to disk.

    Pass --output <path> to write to a custom location (for testing).
    """
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=None,
        help="Write to this path instead of the default location.",
    )
    args = parser.parse_args()

    _ensure_import_path()

    fields = _load_fields()

    if len(fields) != 8:
        print(
            f"ERROR: REBASELINE_RECOVERY_FIELDS has {len(fields)} entries; expected 8.",
            file=sys.stderr,
        )
        return 1
    expected = (
        "action",
        "endpoint",
        "reason",
        "last_known_baseline_graph_hash",
        "submit_graph_hash",
        "submit_structural_graph_hash",
        "client_graph_hash",
        "client_structural_graph_hash",
    )
    if fields != expected:
        print(
            f"ERROR: REBASELINE_RECOVERY_FIELDS does not match expected canonical order.\n"
            f"  got:      {fields!r}\n"
            f"  expected: {expected!r}",
            file=sys.stderr,
        )
        return 1

    js_source = generate_js(fields)

    if args.output:
        output_path = args.output
    else:
        output_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "vibecomfy",
            "comfy_nodes",
            "web",
            "agent_edit_response_contract_generated.js",
        )
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8", newline="") as fh:
        fh.write(js_source)

    print(f"Wrote {output_path} ({len(js_source)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
