// agent_edit_response_contract_generated.js — Generated JS contract (snake_case canonical)
//
// AUTO-GENERATED by python -m tools.generate_agent_contract_js.
// Source of truth: vibecomfy/comfy_nodes/agent/contracts.py
//
// Symbols in this module use snake_case as the canonical wire format,
// matching the Python wire format and the lifecycle module's existing output.
// camelCase input acceptance and camelCase output wrapping are layered on top
// by agent_edit_response_contract.js — they are NOT part of this module.
//
// inferLegacyOutcome is explicitly JS-only and outside the single-source schema.

// ── Internal helpers ────────────────────────────────────────────────────────

function isObject(value) {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function asString(value) {
  return typeof value === "string" ? value : null;
}

// ── Constants (shared, Python-sourced) ──────────────────────────────────────

export const PUBLIC_OUTCOME_KINDS = Object.freeze([
  "candidate",
  "noop",
  "clarify",
  "error"
]);

export const INTERNAL_OUTCOME_KIND_MAP = Object.freeze({
    "edit": "candidate",
    "edit+clarify": "candidate",
});

export const FAILURE_HINT_KEYS = Object.freeze([
  "agent_failure_context",
  "failureKind",
  "failure_kind",
  "nextAction",
  "next_action",
  "retryable"
]);

export const NORMALIZED_RESPONSE_MARKER = "__agentEditResponseNormalized";

// ── Candidate-payload detection ─────────────────────────────────────────────

/**
 * Check whether a raw response contains a candidate payload.
 *
 * candidate_graph is treated as a peer of candidate and graph (rather than
 * nested under .candidate) because it is the canonical snake_case wire
 * container for structured graph data.  This flattening keeps the logic in
 * normalizeCandidateGraph straightforward and avoids a recursive-normalization
 * tangle when a response carries only candidate_graph without a parent
 * candidate envelope.  The decision is deliberate and cross-checked against
 * the Python-side candidate-graph extraction in agent_edit.py.
 *
 * @param {*} response - raw response object
 * @returns {boolean}
 */
export function responseHasCandidatePayload(response) {
  if (!isObject(response)) {
    return false;
  }
  return isObject(response.candidate)
    || isObject(response.candidate_graph)
    || isObject(response.graph);
}

// ── Rebaseline recovery (snake_case canonical) ──────────────────────────────

/**
 * Normalize a raw rebaseline-recovery object to the canonical snake_case shape.
 * Fields not present or non-string are set to null.
 *
 * @param {*} recovery - raw recovery value
 * @returns {object|null} canonical snake_case recovery, or null
 */
export function normalizeRebaselineRecovery(recovery) {
  if (!recovery || typeof recovery !== "object") {
    return null;
  }
  return {
    action: asString(recovery.action),
    endpoint: asString(recovery.endpoint),
    reason: asString(recovery.reason),
    last_known_baseline_graph_hash: asString(recovery.last_known_baseline_graph_hash),
    submit_graph_hash: asString(recovery.submit_graph_hash),
    submit_structural_graph_hash: asString(recovery.submit_structural_graph_hash),
    client_graph_hash: asString(recovery.client_graph_hash),
    client_structural_graph_hash: asString(recovery.client_structural_graph_hash),
  };
}

/**
 * Extract a rebaseline-recovery payload from a response object.
 * Searches snake_case paths only:
 *   1. response.rebaseline_recovery (top-level)
 *   2. response.agent_failure_context.issues[*].rebaseline_recovery
 *   3. response.outcome.agent_failure_context.issues[*].rebaseline_recovery
 *   4. response.debug.failure.agent_failure_context.issues[*].rebaseline_recovery
 *
 * camelCase input paths are NOT handled here — see the pre-pass in
 * agent_edit_response_contract.js for camelCase input acceptance.
 *
 * @param {*} response - raw response object
 * @returns {object|null} canonical snake_case recovery, or null
 */
export function extractRebaselineRecovery(response) {
  const topLevel = normalizeRebaselineRecovery(response?.rebaseline_recovery);
  if (topLevel) {
    return topLevel;
  }
  const issueSources = [
    response?.agent_failure_context?.issues,
    response?.outcome?.agent_failure_context?.issues,
    response?.debug?.failure?.agent_failure_context?.issues,
  ];
  for (const issues of issueSources) {
    if (!Array.isArray(issues)) {
      continue;
    }
    for (const issue of issues) {
      const recovery = normalizeRebaselineRecovery(issue?.rebaseline_recovery);
      if (recovery) {
        return recovery;
      }
    }
  }
  return null;
}
