from __future__ import annotations

from importlib import import_module

# T-037: the batch REPL loop now lives as real functions in edit_batch_repl.py,
# reached through the thin _stage_agent_batch_repl delegate defined below.
# Resolved here via import_module (never through a normal from-import) so there
# is no import cycle: edit_batch_repl imports only stdlib and builds its
# EditBatchReplDeps at call time from this assembled façade namespace
# (globals()).
_edit_batch_repl = import_module(f"{__package__ or 'vibecomfy.comfy_nodes.agent'}.edit_batch_repl")

# T-038/T-039: the foundation fragments (state/humanize/memory/reports/chat/
# session_bundle/ingest/research) and the orchestration fragments (revision,
# revision_stages, batch_loop, transform_stages, narrator, response_contract,
# orchestration, entrypoint) live as real modules imported here in dependency
# order. Each module's __all__ is exactly the name set its fragment contributed
# to this namespace under the old exec assembly, so `import *` reproduces the
# identical top-level attributes.
# T-040: these imports are now the ONLY source of façade names. The exec
# assembler and the fragment SOURCE strings are gone from the live path;
# __all__ below pins the frozen 472-name surface.
from ._frag_state import *  # noqa: F401,F403
from ._frag_humanize import *  # noqa: F401,F403
from ._frag_batch_memory import *  # noqa: F401,F403
from ._frag_batch_reports import *  # noqa: F401,F403
from ._frag_chat import *  # noqa: F401,F403
from ._frag_session_bundle import *  # noqa: F401,F403
from ._frag_ingest import *  # noqa: F401,F403
from ._frag_research import *  # noqa: F401,F403
from ._frag_revision import *  # noqa: F401,F403
from ._frag_revision_stages import *  # noqa: F401,F403
from ._frag_batch_loop import *  # noqa: F401,F403
from ._frag_transform_stages import *  # noqa: F401,F403
from ._frag_narrator import *  # noqa: F401,F403
from ._frag_response_contract import *  # noqa: F401,F403
from ._frag_orchestration import *  # noqa: F401,F403
from ._frag_entrypoint import *  # noqa: F401,F403

# T-039 required_post_split contract: the frozen manifest names
# load_agent_generated_scratchpad as a top-level edit-module attr post-split
# (pre-split it exists only as a guarded local import inside
# _frag_transform_stages._stage_load_python). The lazy facade lives in the
# fragment module; it is re-exported here by name and kept OUT of __all__ so
# the frozen 472-name surface set stays byte-identical (the manifest records
# this name under required_post_split, not __all__).
from ._frag_transform_stages import load_agent_generated_scratchpad


def _stage_agent_batch_repl(
    state: AgentEditState,
    _context: TurnContext,
    *,
    deepseek_client: DeepSeekClient | None = None,
    route: str | None = None,
    model: str | None = None,
    effort: str | None = None,
    client_id: str | None = None,
    conversation_messages: list[dict[str, Any]] | None = None,
) -> StageResult:
    """Batch REPL loop (T-037): thin delegate into edit_batch_repl.

    The loop body moved out of the stitched fragments into
    :mod:`vibecomfy.comfy_nodes.agent.edit_batch_repl`; this S3 stage keeps the
    original signature so orchestration and tests are unaffected. The extracted
    implementation builds its invocation-time :class:`EditBatchReplDeps` from
    this assembled namespace (``globals()``) at the top of each call.
    """
    return _edit_batch_repl._stage_agent_batch_repl(
        globals(),
        state,
        _context,
        deepseek_client=deepseek_client,
        route=route,
        model=model,
        effort=effort,
        client_id=client_id,
        conversation_messages=conversation_messages,
    )


# Frozen ORACLE-1 cleanup surface (T-036, membership-only; order not
# contractual — a frozenset). Source of truth:
# tests/fixtures/agent_edit/cleanup_surface_manifest.json. Every name is a
# top-level attribute of this module, provided by the _frag_* re-exports above
# (or defined in place, as _stage_agent_batch_repl is); the surface test
# enforces set-equality with the manifest so drift fails loudly.
__all__ = frozenset(
    {
        "AgentEditState",
        "AgentError",
        "AgentTurnResult",
        "Any",
        "ApplyCandidate",
        "ApplyEligibility",
        "ArtifactRef",
        "BatchTurnResult",
        "Callable",
        "DEFAULT_CHAT_DISPLAY_MESSAGES",
        "DeepSeekClient",
        "ExecutionPlan",
        "FailureEnvelope",
        "FailureKind",
        "FieldChange",
        "LOGGER",
        "MalformedModelJSON",
        "Mapping",
        "MissingRequiredField",
        "NarrativeContext",
        "PLAN_STATE_NOT_REQUIRED",
        "PROMPT_MEMORY_MESSAGES",
        "Path",
        "PlanEvaluation",
        "ProviderError",
        "REVIEWABLE_CANDIDATE_STATES",
        "ReadinessReport",
        "RevisionEvidence",
        "StageResult",
        "StageSnapshot",
        "TYPE_CHECKING",
        "TerminalClarifySplit",
        "TopologyFindings",
        "TurnContext",
        "TurnIdentity",
        "TurnOutcome",
        "ValidationIssue",
        "_ABSENT_FIELD_OLD",
        "_ADDITIVE_INTENT_PHRASES",
        "_ADDITIVE_INTENT_STANDALONE",
        "_BATCH_EXIT_BUDGET",
        "_BATCH_EXIT_DONE",
        "_BATCH_EXIT_EDIT_CLARIFY",
        "_BATCH_EXIT_NOOP",
        "_BATCH_EXIT_PURE_CLARIFY",
        "_BATCH_PROTOCOL_RETRY_PROMPT",
        "_BATCH_UNREPRESENTABLE_DIAGNOSTIC_CODES",
        "_BUNDLE_MAX_FILE_BYTES",
        "_BUNDLE_MAX_TOTAL_BYTES",
        "_BUNDLE_TEXT_SUFFIXES",
        "_CHAT_REASONING_MAX_DIAGS",
        "_CHAT_REASONING_MAX_OPERATIONS",
        "_CHAT_REASONING_MAX_STEPS",
        "_CLARIFY_CALL_RE",
        "_CLARIFY_FORBIDDEN_RESPONSE_KEYS",
        "_CODE_NODE_TRIGGER_TERMS",
        "_DETAIL_ALIAS_CAP",
        "_DETAIL_LIST_CAP",
        "_DIAGNOSTIC_DETAIL_KEYS",
        "_DISCOVERY_CONSTRUCTION_NUDGE",
        "_DISCOVERY_CONSTRUCTION_NUDGE_THRESHOLD",
        "_GRAPH_EXPLAIN_TRIGGER_TERMS",
        "_MANIFEST_COMPACTOR_MAX_ANCHORS",
        "_MANIFEST_COMPACTOR_MAX_EDGES",
        "_MANIFEST_COMPACTOR_MAX_NODES",
        "_MANIFEST_PRESERVE_INSTRUCTIONS",
        "_MAX_EXECUTION_PROTOCOL_LIST_ITEMS",
        "_MAX_EXECUTION_PROTOCOL_SOURCES",
        "_MAX_EXECUTION_PROTOCOL_STRING",
        "_MISSING_FIELD_CHANGE_OLD",
        "_NARRATIVE_COUNT_PATTERN",
        "_NARRATIVE_EDIT_CLAIM_PATTERNS",
        "_NARRATIVE_GATE_JARGON_PATTERNS",
        "_NARRATIVE_NO_EDIT_PATTERNS",
        "_NARRATIVE_QUESTION_START",
        "_NARRATIVE_VALIDATION_FAIL_PATTERNS",
        "_NARRATIVE_VALIDATION_PASS_PATTERNS",
        "_NARRATOR_DEFAULT_MODEL",
        "_NARRATOR_DEFAULT_ROUTE",
        "_NARRATOR_RESPONSE_REQUIRED_FIELD",
        "_NARRATOR_SYSTEM_PROMPT",
        "_PARAMETER_TWEAK_ACTION_TERMS",
        "_PARAMETER_TWEAK_TARGET_TERMS",
        "_RESEARCH_TRIGGER_TERMS",
        "_RUNTIME_OBJECT_INFO_PATH",
        "_SEARCH_CALL_RE",
        "_SEARCH_KW_RE",
        "_SESSION_ROOT",
        "_StageBlocked",
        "_TEXT_TO_IMAGE_SEED_TYPES",
        "_WARNED_IGNORED_PUBLIC_PROTOCOL_ENVS",
        "_WARNED_LEGACY_CONTRACTS",
        "_actionable_plan_dependency_status",
        "_actionable_plan_required_new_classes",
        "_actionable_plan_ui_only_classes",
        "_active_manifest_from_plan",
        "_adaptation_slice_domain_mismatch_diagnostic",
        "_agent_edit_batch_repl_enabled",
        "_agent_edit_contract",
        "_agent_edit_turn_event_payload",
        "_agent_edit_v2_enabled",
        "_append_post_edit_reorganisation_advice",
        "_article_for",
        "_artifact",
        "_assemble_narrative_context",
        "_batch_budget_artifixer_report",
        "_batch_budget_failure_kind",
        "_batch_candidate_graph_changed",
        "_batch_has_landed_edits",
        "_batch_protocol_parse_reason",
        "_batch_protocol_retry_messages",
        "_batch_repl_candidate_needs_queue_validate",
        "_batch_research_memory_summary",
        "_batch_turn_diagnostics",
        "_batch_warning_sentence",
        "_brief_batch_statements",
        "_build_batch_repl_failure_response",
        "_build_batch_repl_response",
        "_build_candidate_payload",
        "_build_compatibility_response_fields",
        "_build_cumulative_batch_repl_delta_envelope",
        "_build_dev_failure_response",
        "_build_dev_success_response",
        "_build_graph_report",
        "_build_lowering_audit_entries",
        "_build_lowering_change_entries",
        "_build_lowering_recovery_entries",
        "_build_narrator_messages",
        "_build_object_info_in_process",
        "_build_precedent_adaptation_prompt",
        "_build_precedent_semantic_check_entries",
        "_build_topology_manifest_prompt_block",
        "_call_narrator_llm",
        "_can_attempt_direct_existing_parameter_tweak",
        "_can_attempt_local_additive_revise",
        "_candidate_dict",
        "_candidate_full_ui_payload_changed",
        "_candidate_stable_key",
        "_canonical_agent_edit_route",
        "_canonical_delta_ops_envelope_payload",
        "_cap_diagnostic_detail",
        "_change_details_payload",
        "_change_subject",
        "_clarification_payload",
        "_class_names_from_text",
        "_classify_stage_failure",
        "_compact_change_details_payload",
        "_compact_chat_change_details",
        "_compact_diag_to_dict",
        "_compact_diag_with_capped_detail",
        "_compact_execution_protocol_notes_for_prompt",
        "_compact_protocol_jsonish",
        "_compact_protocol_list",
        "_compact_protocol_string",
        "_compact_research_source_for_prompt",
        "_consecutive_discovery_only_turn_count",
        "_contains_clarify_call",
        "_conversation_with_candidate_reference",
        "_copy_compact_protocol_fields",
        "_decode_clarify_literal",
        "_default_runtime_schema_provider",
        "_dependency_graph_class_types",
        "_deterministic_narrative_fallback",
        "_direct_existing_parameter_tweak_feedback",
        "_discovery_construction_nudge",
        "_discovery_stop_message",
        "_display_value",
        "_duplicate_search_cycle_feedback",
        "_duration_ms",
        "_edit_lint_enabled",
        "_edit_noop_requires_graph_evidence_feedback",
        "_effective_implementation_task",
        "_emit_agent_edit_turn_event",
        "_empty_graph_authoring_request",
        "_enrich_schema_provider_from_resolver_candidates",
        "_ensure_canonical_delta_ops",
        "_evaluate_execution_plan_after_candidate_update",
        "_execution_plan_artifact_refs",
        "_execution_plan_debug_fields",
        "_execution_plan_done_refusal_hint",
        "_execution_plan_response_fields",
        "_execution_plan_status_for_prompt",
        "_execution_plan_task_satisfaction_entries",
        "_executor_classification_text",
        "_executor_requested_implementation",
        "_existing_parameter_tweak_targets",
        "_existing_parameter_tweak_targets_from_graph",
        "_extract_clarify_message",
        "_extract_readiness_diagnostics",
        "_extract_ready_metadata",
        "_extract_search_signatures",
        "_failure_response",
        "_fallback_narrative_message",
        "_field_change_is_noop",
        "_field_changes_payload",
        "_finalize_revision_evidence_with_candidate",
        "_first_link_source_label",
        "_focus_types_from_research_brief",
        "_focus_types_from_research_sources",
        "_format_available_node_names",
        "_format_batch_report",
        "_format_batch_report_json",
        "_format_clarify_markdown_message",
        "_format_diagnostic_detail_text",
        "_format_node_variable_index",
        "_format_query_output",
        "_format_research_brief_for_prompt",
        "_format_statement_source",
        "_graph_class_types",
        "_graph_class_types_missing_from_schema",
        "_guard_narrative_message",
        "_has_enough_grounded_facts_for_dev_narrative",
        "_human_change_phrase",
        "_humanized_edit_message",
        "_humanized_noop_message",
        "_hydrate_actionable_registry_dependencies",
        "_hydrate_current_graph_unknown_node_schemas",
        "_hydrate_execution_plan_from_protocol_notes",
        "_hydrate_research_precedent_node_schemas",
        "_inject_lowering_provenance",
        "_is_code_node_intent",
        "_is_done_expr",
        "_is_graph_explain_intent",
        "_is_link_endpoint",
        "_is_provider_exception",
        "_is_research_intent",
        "_is_terminal_clarify_expr",
        "_is_ui_only_annotation_class_type",
        "_iter_research_precedent_sources",
        "_iter_ui_graph_nodes",
        "_iter_ui_nodes",
        "_join_human_list",
        "_json_safe",
        "_landed_edit_lead",
        "_latest_clarification_context",
        "_latest_session_candidate_payload",
        "_latest_turn_lifecycle_payload",
        "_layout_only_reorganise_evidence_changed",
        "_legacy_failure_response",
        "_legacy_narrative_debug_status",
        "_link_endpoint_parts",
        "_lint_diag_with_capped_detail",
        "_localized_additive_scoped_evidence",
        "_looks_internal_uid",
        "_malformed_model_json_detail",
        "_manifest_compact_payload",
        "_manifest_is_complete",
        "_manifest_required_new_classes",
        "_narrate_final_message",
        "_narrative_artifact_path",
        "_narrative_artifact_refs",
        "_narrative_context_payload",
        "_narrative_debug_fields",
        "_narrative_issue_payloads",
        "_narrative_issue_summary",
        "_narrative_research_payload",
        "_narrative_revision_payload",
        "_narrative_stage_payload",
        "_narrator_fast_path_applies",
        "_narrator_message_from_response",
        "_narrator_model",
        "_narrator_route",
        "_narrator_system_message",
        "_narrator_user_message",
        "_net_field_changes",
        "_node_class_label",
        "_node_key_values",
        "_node_label_by_uid",
        "_node_phrase",
        "_noop_field_changes",
        "_normalize_test_client_batch_response",
        "_normalize_test_client_response",
        "_offset_from_ast_position",
        "_operation_detail_payload",
        "_plan_validation_allows_candidate",
        "_port_issue_to_dict",
        "_post_edit_reorganisation_advice_sentence",
        "_post_edit_reorganisation_public_advisory",
        "_prefetch_research_summary",
        "_premature_missing_custom_node_clarify_feedback",
        "_premature_workflow_schema_clarify_feedback",
        "_prepare_narrative_artifact_paths",
        "_present_class_types",
        "_product_failure_response",
        "_queue_recovery_report_for_candidate",
        "_re",
        "_read_only_discovery_turn_count",
        "_read_turn_response_payload",
        "_real_field_changes",
        "_record",
        "_record_narrative_artifacts",
        "_record_post_edit_reorganisation_advisory",
        "_recovery_report_from_ui_payload",
        "_render_batch_diff",
        "_repair_field_changes_from_original_ui",
        "_request_no_gpu_detected",
        "_resolve_endpoint_label",
        "_resolve_output_slot_name",
        "_resolver_candidate_is_authoring_capability",
        "_resolver_candidate_supports_class",
        "_resolver_candidates_from_batch_result",
        "_resolver_candidates_from_batch_turns",
        "_response_apply_eligibility",
        "_response_artifacts_with_execution_plan",
        "_response_contract_candidate_present",
        "_retry_after_dependency_preflight_failure",
        "_revision_candidate_retry_hint",
        "_revision_evidence_artifact_payload",
        "_revision_evidence_prompt_json",
        "_revision_no_candidate_reason",
        "_revision_readonly_message",
        "_revision_rejected_candidate_message",
        "_revision_target_node_ids",
        "_route_blocks_apply",
        "_route_change_focus_label",
        "_run_batch_repl_product_path",
        "_run_batch_repl_queue_validate_if_needed",
        "_run_delta_dev_path",
        "_run_full_dev_path",
        "_run_stage",
        "_runtime_code_additive_request",
        "_runtime_execution_requested",
        "_safe_session_id",
        "_sanitize_pure_clarify_response",
        "_schema_provider_available",
        "_schema_provider_has_class",
        "_seed_focus_types_for_authoring",
        "_selected_precedent_unknown_class_feedback",
        "_semantic_validation_description",
        "_sentence_case",
        "_session_artifact_response_fields",
        "_session_reference_map_for_evidence",
        "_split_terminal_clarify_line_regex",
        "_stable_blocker_key",
        "_stage_agent",
        "_stage_agent_batch_repl",
        "_stage_agent_delta",
        "_stage_apply_delta",
        "_stage_audit",
        "_stage_batch_repl_queue_validate",
        "_stage_convert",
        "_stage_emit",
        "_stage_ingest",
        "_stage_ingest_v2",
        "_stage_load_python",
        "_stage_lower",
        "_stage_project_v2",
        "_stage_readonly_diagnostic_report",
        "_stage_revision_evidence",
        "_stage_revision_readonly_report",
        "_stage_snapshot_payloads",
        "_stage_summarize",
        "_stage_summarize_v2",
        "_stage_validate",
        "_stale_rebaseline_recovery_issue",
        "_stamp_identity_on_original",
        "_stamped_message_outcome",
        "_stamped_turn_response_outcome",
        "_state_runtime_execution_requested",
        "_strip_clarify_forbidden_response_fields",
        "_structural_change_phrases",
        "_structural_validation_description",
        "_subtract_existing_blockers",
        "_summarize_precedent_packet",
        "_sync_narrated_clarify_outcome",
        "_synthesize_batch_repl_message",
        "_synthesize_post_validation_narrative",
        "_targeted_edit_hardening_feedback",
        "_task_looks_like_additive",
        "_task_looks_like_parameter_tweak",
        "_task_mentions_any",
        "_terminal_answer_message",
        "_total_landed_edit_count",
        "_transaction_receipts_for_turn",
        "_trim_chat_text",
        "_turn_is_discovery_only_no_edit",
        "_ui_display_widget_value_for_field",
        "_ui_node_by_uid",
        "_ui_node_uid",
        "_ui_node_uid_aliases",
        "_ui_widget_value_for_field",
        "_v2_candidate_mutation_plan_fields",
        "_validate_delta_evidence_for_apply",
        "_validate_narrative_message",
        "_validated_agent_edit_response",
        "_validation_summary_payload",
        "_warn_ignored_public_protocol_envs_once",
        "_warn_legacy_contract_once",
        "_workflow_class_types_from_research_context",
        "_workflow_schema_candidates_from_batch_result",
        "_workflow_schema_candidates_from_research_context",
        "_workflow_schema_classes_from_context",
        "_workflow_schema_relevant_clarify",
        "_write_narrative_artifacts",
        "_write_revision_evidence_artifact",
        "_write_turn_chat_artifact",
        "_write_unknown_transition_audits",
        "_ws_send",
        "allocate_turn",
        "annotations",
        "apply_stage_gate_updates",
        "artifact_ref_for_path",
        "ast",
        "base64",
        "build_batch_messages",
        "build_delta_messages",
        "build_legacy_agent_edit_v1",
        "build_messages",
        "classify_failure",
        "classify_legacy_migration_v1",
        "collect_graph_facts",
        "collect_readiness_evidence",
        "collect_topology_evidence",
        "compute_scoped_diff",
        "dataclass",
        "dataclasses",
        "datetime",
        "derive_apply_eligibility",
        "derive_gates",
        "difflib",
        "ensure_agent_edit_response_contract",
        "ensure_sentence_message",
        "evaluate_execution_plan_for_state",
        "failure_envelope",
        "field",
        "format_compact_plan_feedback",
        "format_compact_plan_status",
        "handle_agent_edit",
        "hydrate_execution_plan_from_protocol_notes",
        "initialize_gates",
        "is_actionable_adaptation_plan",
        "json",
        "load_candidate_transaction",
        "load_candidate_transaction_with_migration",
        "logging",
        "lower_stage_result",
        "node_settings_for",
        "normalize_agent_edit_v2_metadata",
        "normalize_session_id",
        "os",
        "payload_hash",
        "product_failure_envelope_fields",
        "project_transaction_state",
        "public_outcome_from_turn_outcome",
        "queue_stage_result",
        "re",
        "read_session_bundle",
        "read_session_chat",
        "read_session_json",
        "read_state",
        "record_idempotent_response",
        "repair_field_changes",
        "run_agent_turn",
        "run_agent_turn_batch",
        "run_agent_turn_delta",
        "run_model_turn",
        "session_dir_for",
        "split_terminal_clarify",
        "structural_graph_hash",
        "success_envelope",
        "time",
        "timezone",
        "turn_dir_for",
        "turn_envelope",
        "update_plan_validate_gate",
        "update_state_match_gate",
        "uuid",
        "v2_mutation_plan_hash",
        "validation_errors_payload",
        "write_allocation_failure_audit",
        "write_audit",
        "write_json_artifact",
    }
)
